[package]
name = "zbobr-config"
version = "0.1.0"
edition = "2024"

[dependencies]
zbobr-dispatcher = { workspace = true }
zbobr-task-backend-github = { workspace = true }
zbobr-task-backend-fs = { workspace = true }
# zbobr-repo-backend-github = { workspace = true }
zbobr-repo-backend-fs = { workspace = true }
zbobr-executor-claude = { workspace = true }
zbobr-executor-copilot = { workspace = true }
zbobr-executor-mcp-tester = { workspace = true }
zbobr-utility = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
