[workspace]
resolver = "3"
#members = ["zbobr-dispatcher", "zbobr-executor-copilot", "zbobr-executor-claude", "zbobr-executor-mcp-tester", "zbobr-task-backend-github", "zbobr-task-backend-fs", "zbobr-repo-backend-github", "zbobr-repo-backend-fs", "zbobr-api", "zbobr-macros", "zbobr-utility", "zbobr"]
members = ["zbobr-dispatcher", "zbobr-executor-copilot", "zbobr-executor-claude", "zbobr-executor-mcp-tester", "zbobr-task-backend-github", "zbobr-task-backend-fs", "zbobr-repo-backend-github", "zbobr-repo-backend-fs", "zbobr-api", "zbobr-macros", "zbobr-utility", "zbobr-config", "zbobr"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
zbobr-dispatcher = { path = "zbobr-dispatcher" }
zbobr-task-backend-github = { path = "zbobr-task-backend-github" }
zbobr-task-backend-fs = { path = "zbobr-task-backend-fs" }
zbobr-repo-backend-github = { path = "zbobr-repo-backend-github" }
zbobr-repo-backend-fs = { path = "zbobr-repo-backend-fs" }
zbobr-api = { path = "zbobr-api" }
zbobr-config = { path = "zbobr-config" }
zbobr-executor-copilot = { path = "zbobr-executor-copilot" }
zbobr-executor-claude = { path = "zbobr-executor-claude" }
zbobr-executor-mcp-tester = { path = "zbobr-executor-mcp-tester" }
zbobr-utility = { path = "zbobr-utility" }
zbobr-macros = { path = "zbobr-macros" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1.89"
rmcp = { version = "0.17", features = ["server", "macros", "transport-streamable-http-server"] }
axum = "0.8"
schemars = "1"
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive", "env"] }
reqwest = { version = "0.13.2", features = ["json", "blocking", "cookies"] }
rustls = { version = "0.23.37", features = ["ring"] }
toml = "0.9.8"
tempfile = "3.26"
hostname = "0.4"
paste = "1.0"
