[package]
name = "zbobr-repo-backend-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
zbobr-api = { workspace = true }
anyhow = { workspace = true }
zbobr-utility = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_yaml = "0.9"
tracing = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
paste = { workspace = true }

[dev-dependencies]
zbobr-api = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_yaml = "0.9"
