use std::{collections::HashMap, path::PathBuf};

use indexmap::IndexMap;
use zbobr_utility::config_struct;

use crate::{
    config_tools::McpTool,
    task::{Model, Pipeline, Stage, Tool},
};

/// Auto-generated by #[config_struct] for every config struct.
pub trait Config: Sized {
    type Toml: Default + for<'de> serde::Deserialize<'de>;
    type Args: clap::Args + zbobr_utility::PrefixedArgs + Default + Clone;
    fn build(toml: Option<Self::Toml>, args: Self::Args, config_dir: &std::path::Path) -> Self;
}

/// Definition of a role: which MCP tools it can access, an optional prompt file, and default tool/model.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct RoleDefinition {
    pub mcp: Vec<McpTool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<PathBuf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_tool: Option<Tool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_model: Option<Model>,
}

/// A stage transition descriptor with an optional target stage and pause flag.
///
/// Accepts two TOML forms:
/// - String shorthand: `on_success = "stage_b"` → `{ next: Some("stage_b"), pause: false }`
/// - Full table: `on_success = { next = "stage_b", pause = true }`
///
/// Both `next` and `pause` are optional (defaults: `None` and `false`).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize)]
pub struct StageTransition {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<Stage>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub pause: bool,
}

impl StageTransition {
    pub fn stage(next: impl Into<Stage>) -> Self {
        Self {
            next: Some(next.into()),
            pause: false,
        }
    }

    pub fn pause() -> Self {
        Self {
            next: None,
            pause: true,
        }
    }
}

impl<'de> serde::Deserialize<'de> for StageTransition {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(serde::Deserialize)]
        #[serde(deny_unknown_fields)]
        struct FullTransition {
            #[serde(default)]
            next: Option<Stage>,
            #[serde(default)]
            pause: bool,
        }
        #[derive(serde::Deserialize)]
        #[serde(untagged)]
        enum Helper {
            Stage(Stage),
            Full(FullTransition),
        }
        match Helper::deserialize(deserializer)? {
            Helper::Stage(s) => Ok(StageTransition {
                next: Some(s),
                pause: false,
            }),
            Helper::Full(f) => Ok(StageTransition {
                next: f.next,
                pause: f.pause,
            }),
        }
    }
}

/// A single stage in the configurable pipeline.
///
/// The stage's name and pipeline are derived from its structural position
/// (key in the stages HashMap and key in the pipelines HashMap).
///
/// A stage must have exactly one of `role` (run an agent session) or
/// `call` (call another pipeline). They are mutually exclusive.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Default)]
#[serde(deny_unknown_fields)]
pub struct StageDefinition {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call: Option<Pipeline>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<Model>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<Tool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_prompt: Option<PathBuf>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub prompts: Vec<PathBuf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_success: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_failure: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_intermediate: Option<StageTransition>,
}

impl StageDefinition {
    pub fn role_name(&self) -> Option<&str> {
        self.role.as_deref()
    }

    pub fn call_pipeline(&self) -> Option<&Pipeline> {
        self.call.as_ref()
    }

    pub fn is_call(&self) -> bool {
        self.call.is_some()
    }

    pub fn on_success(&self) -> Option<&StageTransition> {
        self.on_success.as_ref()
    }

    pub fn on_failure(&self) -> Option<&StageTransition> {
        self.on_failure.as_ref()
    }

    pub fn on_intermediate(&self) -> Option<&StageTransition> {
        self.on_intermediate.as_ref()
    }
}

/// Per-pipeline configuration: an ordered sequence of stages.
///
/// Stage order is determined by insertion order in the `IndexMap`.
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct PipelineConfig {
    #[serde(default)]
    pub stages: IndexMap<Stage, StageDefinition>,
}

impl PipelineConfig {
    /// Look up a stage by name.
    pub fn stage(&self, name: &str) -> Option<&StageDefinition> {
        self.stages.get(name)
    }

    /// Get the index of a stage in the order.
    pub fn stage_index(&self, name: &str) -> Option<usize> {
        self.stages.get_index_of(name)
    }

    /// Get the next stage after `name`.
    pub fn next_stage(&self, name: &str) -> Option<(&str, &StageDefinition)> {
        let idx = self.stages.get_index_of(name)?;
        let (next_name, def) = self.stages.get_index(idx + 1)?;
        Some((next_name.as_str(), def))
    }

    /// Get the first stage of this pipeline.
    pub fn first_stage(&self) -> Option<(&str, &StageDefinition)> {
        let (name, def) = self.stages.first()?;
        Some((name.as_str(), def))
    }

    /// Get the start stage for this pipeline (delegates to first_stage).
    pub fn start_stage(&self) -> Option<(&str, &StageDefinition)> {
        self.first_stage()
    }

    /// Validate pipeline configuration.
    pub fn validate(&self, pipeline_name: &str) -> anyhow::Result<()> {
        if self.stages.is_empty() {
            anyhow::bail!("Pipeline '{}' has no stages", pipeline_name);
        }
        for (sname, stage) in &self.stages {
            match (&stage.role, &stage.call) {
                (Some(_), Some(_)) => anyhow::bail!(
                    "Pipeline '{}' stage '{}' has both 'role' and 'call' — only one is allowed",
                    pipeline_name,
                    sname
                ),
                (None, None) => anyhow::bail!(
                    "Pipeline '{}' stage '{}' has neither 'role' nor 'call' — one is required",
                    pipeline_name,
                    sname
                ),
                _ => {}
            }
            if let Some(ref target) = stage.on_success.as_ref().and_then(|t| t.next.as_ref()) {
                if !self.stages.contains_key(target.as_str()) {
                    anyhow::bail!(
                        "Pipeline '{}' stage '{}' on_success references unknown stage '{}'",
                        pipeline_name,
                        sname,
                        target
                    );
                }
            }
            if let Some(ref target) = stage.on_failure.as_ref().and_then(|t| t.next.as_ref()) {
                if !self.stages.contains_key(target.as_str()) {
                    anyhow::bail!(
                        "Pipeline '{}' stage '{}' on_failure references unknown stage '{}'",
                        pipeline_name,
                        sname,
                        target
                    );
                }
            }
            if let Some(ref target) = stage.on_intermediate.as_ref().and_then(|t| t.next.as_ref()) {
                if !self.stages.contains_key(target.as_str()) {
                    anyhow::bail!(
                        "Pipeline '{}' stage '{}' on_intermediate references unknown stage '{}'",
                        pipeline_name,
                        sname,
                        target
                    );
                }
            }
        }
        Ok(())
    }
}

/// Top-level workflow configuration: a container of named pipelines and shared roles.
///
/// Defined manually (not via `#[config_struct]`) because it needs
/// custom `Config` impl with `WorkflowArgs` / `WorkflowToml`.
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowConfig {
    /// Base directory for prompt files; prepended to relative prompt paths.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompts_dir: Option<PathBuf>,
    #[serde(default)]
    pub roles: IndexMap<String, RoleDefinition>,
    #[serde(default)]
    pub pipelines: HashMap<Pipeline, PipelineConfig>,
}

/// TOML representation of WorkflowConfig (all fields optional).
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowToml {
    #[serde(default)]
    pub prompts_dir: Option<PathBuf>,
    #[serde(default)]
    pub roles: Option<IndexMap<String, RoleDefinition>>,
    #[serde(default)]
    pub pipelines: Option<HashMap<Pipeline, PipelineConfig>>,
}

/// CLI arguments for WorkflowConfig (empty — no CLI-overridable fields).
#[derive(Clone, Debug, Default)]
pub struct WorkflowArgs;

impl clap::Args for WorkflowArgs {
    fn augment_args(cmd: clap::Command) -> clap::Command {
        cmd
    }
    fn augment_args_for_update(cmd: clap::Command) -> clap::Command {
        cmd
    }
}

impl clap::FromArgMatches for WorkflowArgs {
    fn from_arg_matches(_matches: &clap::ArgMatches) -> Result<Self, clap::Error> {
        Ok(WorkflowArgs)
    }
    fn update_from_arg_matches(&mut self, _matches: &clap::ArgMatches) -> Result<(), clap::Error> {
        Ok(())
    }
}

impl zbobr_utility::PrefixedArgs for WorkflowArgs {
    fn augment_args_prefixed(cmd: clap::Command, _prefix: &str) -> clap::Command {
        cmd
    }
    fn from_matches_prefixed(
        _matches: &clap::ArgMatches,
        _prefix: &str,
    ) -> Result<Self, clap::Error> {
        Ok(WorkflowArgs)
    }
}

impl WorkflowArgs {
    pub fn has_overrides(&self) -> bool {
        false
    }
}

impl WorkflowToml {
    pub fn merge_with_args(self, _args: WorkflowArgs) -> Self {
        self
    }

    pub fn try_into_config(self) -> anyhow::Result<WorkflowConfig> {
        Ok(WorkflowConfig {
            prompts_dir: self.prompts_dir,
            roles: self.roles.unwrap_or_default(),
            pipelines: self.pipelines.unwrap_or_default(),
        })
    }
}

impl Config for WorkflowConfig {
    type Toml = WorkflowToml;
    type Args = WorkflowArgs;

    fn build(toml: Option<Self::Toml>, _args: Self::Args, _config_dir: &std::path::Path) -> Self {
        match toml {
            Some(t) => WorkflowConfig {
                prompts_dir: t.prompts_dir,
                roles: t.roles.unwrap_or_default(),
                pipelines: t.pipelines.unwrap_or_default(),
            },
            None => WorkflowConfig::default(),
        }
    }
}

impl WorkflowConfig {
    /// Look up a pipeline by name.
    pub fn pipeline(&self, name: impl Into<Pipeline>) -> Option<&PipelineConfig> {
        self.pipelines.get(name.into().as_str())
    }

    /// Look up a stage in a specific pipeline.
    pub fn stage(&self, pipeline: impl Into<Pipeline>, stage: &str) -> Option<&StageDefinition> {
        self.pipelines.get(pipeline.into().as_str())?.stage(stage)
    }

    /// Get the start stage for a pipeline.
    pub fn start_stage_for_pipeline(
        &self,
        pipeline: impl Into<Pipeline>,
    ) -> Option<(&str, &StageDefinition)> {
        self.pipelines.get(pipeline.into().as_str())?.start_stage()
    }

    /// The default pipeline name.
    pub fn default_pipeline(&self) -> Pipeline {
        Pipeline::Main
    }

    /// All pipeline names.
    pub fn pipeline_names(&self) -> Vec<&Pipeline> {
        let mut names: Vec<&Pipeline> = self.pipelines.keys().collect();
        names.sort();
        names
    }

    /// Find the first stage with a given role (across all pipelines, preferring default pipeline).
    pub fn find_stage_by_role(&self, role: &str) -> Option<(&Pipeline, &str, &StageDefinition)> {
        let default = self.default_pipeline();
        if let Some(pipeline) = self.pipelines.get(default.as_str()) {
            if let Some((name, stage)) = pipeline
                .stages
                .iter()
                .find(|(_, s)| s.role_name() == Some(role))
            {
                return self
                    .pipelines
                    .get_key_value(default.as_str())
                    .map(|(p, _)| (p, name.as_str(), stage));
            }
        }
        for (pname, pipeline) in &self.pipelines {
            if let Some((sname, stage)) = pipeline
                .stages
                .iter()
                .find(|(_, s)| s.role_name() == Some(role))
            {
                return Some((pname, sname.as_str(), stage));
            }
        }
        None
    }

    /// Look up a role definition by name.
    pub fn role_definition(&self, role: &str) -> Option<&RoleDefinition> {
        self.roles.get(role)
    }

    /// Iterate over all stages as `(pipeline_name, stage_name, &StageDefinition)` tuples.
    pub fn all_stages(&self) -> Vec<(&Pipeline, &str, &StageDefinition)> {
        let mut result = Vec::new();
        for (pname, pipeline) in &self.pipelines {
            for (sname, stage) in &pipeline.stages {
                result.push((pname, sname.as_str(), stage));
            }
        }
        result
    }

    /// All static tool names.
    pub fn all_tool_names(&self) -> Vec<String> {
        McpTool::all().iter().map(|t| t.to_string()).collect()
    }

    /// Validate the entire workflow configuration.
    pub fn validate(&self) -> anyhow::Result<()> {
        // Required pipelines must exist
        for required in [Pipeline::Main, Pipeline::Merge] {
            if !self.pipelines.contains_key(required.as_str()) {
                anyhow::bail!(
                    "Required pipeline '{}' is missing from [workflow.pipelines]",
                    required
                );
            }
        }

        let pipeline_names = self.pipeline_names();

        // Each pipeline must have valid order/stages
        for pname in &pipeline_names {
            let pipeline = self.pipelines.get(pname.as_str()).unwrap();
            pipeline.validate(pname.as_str())?;
        }

        // Every role-stage's role must exist in the roles map (if roles are configured)
        if !self.roles.is_empty() {
            for (pname, pipeline) in &self.pipelines {
                for (sname, stage) in &pipeline.stages {
                    if let Some(role) = &stage.role {
                        if !self.roles.contains_key(role) {
                            anyhow::bail!(
                                "Stage '{}/{}' references unknown role '{}' (not in [workflow.roles])",
                                pname,
                                sname,
                                role
                            );
                        }
                    }
                }
            }
        }

        // Every call-stage's target pipeline must exist
        for (pname, pipeline) in &self.pipelines {
            for (sname, stage) in &pipeline.stages {
                if let Some(target) = &stage.call {
                    if !self.pipelines.contains_key(target.as_str()) {
                        anyhow::bail!(
                            "Stage '{}/{}' calls unknown pipeline '{}'",
                            pname,
                            sname,
                            target
                        );
                    }
                }
            }
        }

        Ok(())
    }
}

/// Configuration for the zbobr dispatcher.
#[derive(Clone)]
#[config_struct]
pub struct ZbobrDispatcherConfig {
    /// Workspaces directory; each task gets a separate subdirectory.
    #[config(path)]
    pub workspaces: std::path::PathBuf,
    /// Base port for the MCP server; zbobr scans upward from this port to find
    /// an available one.
    #[arg(default_value = "3000")]
    pub base_port: u16,
    /// Read-only GitHub token passed as GH_TOKEN/GITHUB_TOKEN to agent processes.
    /// This is a security boundary: it limits what agents can do on GitHub — agents must
    /// not have write access so that erroneous or misbehaving agents cannot modify remote
    /// repositories. Use a fine-grained token with read-only scopes (or no scopes at all
    /// for fully offline/mcp-tester runs). Defaults to "not-configured" when omitted.
    pub agent_github_token: String,
    /// CLI tool to use as a global default. Individual stages may override this.
    pub tool: Tool,
    /// Global AI model to use when a stage does not specify an override.
    pub model: Model,
    /// Prefix for work branches (default: "zbobr_fix").
    pub work_branch_prefix: String,
    /// Default destination repository (e.g. "owner/repo" or a full git URL).
    /// Used by `configure_worktree` as a fallback when the agent doesn't provide one.
    pub default_destination_repository: Option<String>,
    /// Default destination branch (e.g. "main").
    /// Used by `configure_worktree` as a fallback when the agent doesn't provide one.
    pub default_destination_branch: Option<String>,
    /// Git user name for commits made by the tool.
    pub git_user_name: String,
    /// Git user email for commits made by the tool.
    pub git_user_email: String,
    /// Rewrite commit authors after each stage completes to match configured git user.
    pub overwrite_author: bool,
    /// Maximum number of stages a task is allowed to pass before being auto-paused.
    /// When a task's stage_count reaches this limit, the task is paused automatically.
    /// Set to 0 to disable the limit. Default: 20.
    #[arg(default_value = "20")]
    pub max_task_stage_count: u64,
}

impl Default for ZbobrDispatcherConfig {
    fn default() -> Self {
        Self {
            workspaces: std::path::PathBuf::from("./workspaces"),
            base_port: 3000,
            agent_github_token: "not-configured".to_string(),
            tool: Tool::default(),
            model: Model::default(),
            work_branch_prefix: "zbobr_fix".to_string(),
            default_destination_repository: None,
            default_destination_branch: None,
            git_user_name: String::new(),
            git_user_email: String::new(),
            overwrite_author: false,
            max_task_stage_count: 20,
        }
    }
}

impl ZbobrDispatcherConfig {
    /// Load configuration from environment variables only (backward compat).
    pub fn from_env() -> anyhow::Result<Self> {
        let cwd = std::env::current_dir()
            .map_err(|e| anyhow::anyhow!("Cannot get current directory: {e}"))?;
        Ok(<Self as Config>::build(
            None,
            ZbobrDispatcherArgs::default(),
            &cwd,
        ))
    }

    /// Validate that global tool/model are compatible.
    pub fn validate(&self) -> anyhow::Result<()> {
        if self.model.model_name_for_tool(self.tool).is_none() {
            anyhow::bail!(
                "Global model {:?} is not supported by global tool {:?}",
                self.model,
                self.tool
            );
        }
        Ok(())
    }

    /// Determine which tool to use for a stage, falling back to role default, then global default.
    pub fn tool_for_stage(&self, stage_def: &StageDefinition, workflow: &WorkflowConfig) -> Tool {
        if let Some(tool) = stage_def.tool {
            tool
        } else if let Some(role_name) = stage_def.role_name() {
            if let Some(role_def) = workflow.role_definition(role_name) {
                if let Some(tool) = role_def.default_tool {
                    tool
                } else {
                    self.tool
                }
            } else {
                self.tool
            }
        } else {
            self.tool
        }
    }

    /// Determine which model to use for a stage, falling back to role default, then global default.
    pub fn model_for_stage(&self, stage_def: &StageDefinition, workflow: &WorkflowConfig) -> Model {
        if let Some(model) = stage_def.model.as_ref() {
            model.clone()
        } else if let Some(role_name) = stage_def.role_name() {
            if let Some(role_def) = workflow.role_definition(role_name) {
                if let Some(model) = role_def.default_model.as_ref() {
                    model.clone()
                } else {
                    self.model.clone()
                }
            } else {
                self.model.clone()
            }
        } else {
            self.model.clone()
        }
    }
}
