use zbobr_utility::config_struct;

use crate::task::{Model, Role, Tool};

/// Helper structure for per-stage configuration (tool and model).
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Default)]
#[config_struct]
pub struct StageConfig {
    /// Optional tool override for this stage. Falls back to the global `cli_tool`.
    pub tool: Option<Tool>,
    /// Optional model override for this stage. Applies to the chosen tool's default model.
    pub model: Option<Model>,
}

/// Prompt file configuration. Each role has its own list of prompt file paths.
/// Paths are resolved relative to `path` (base directory) at load time.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Default)]
#[config_struct]
pub struct PromptsConfig {
    /// Base directory for resolving relative prompt file paths.
    #[config(path)]
    pub path: Option<std::path::PathBuf>,
    /// Prompt files for the preparator stage.
    #[serde(default)]
    pub preparator: Vec<std::path::PathBuf>,
    /// Prompt files for the planner stage.
    #[serde(default)]
    pub planner: Vec<std::path::PathBuf>,
    /// Prompt files for the worker stage.
    #[serde(default)]
    pub worker: Vec<std::path::PathBuf>,
    /// Prompt files for the reviewer stage.
    #[serde(default)]
    pub reviewer: Vec<std::path::PathBuf>,
    /// Prompt files for the tester stage.
    #[serde(default)]
    pub tester: Vec<std::path::PathBuf>,
    /// Prompt files for the merger stage.
    #[serde(default)]
    pub merger: Vec<std::path::PathBuf>,
}

impl PromptsConfig {
    /// Get prompt file paths for a given role.
    pub fn prompts_for_role(&self, role: Role) -> &[std::path::PathBuf] {
        match role {
            Role::Preparator => &self.preparator,
            Role::Planner => &self.planner,
            Role::Worker => &self.worker,
            Role::Reviewer => &self.reviewer,
            Role::Tester => &self.tester,
            Role::Merger => &self.merger,
        }
    }
}

/// Auto-generated by #[config_struct] for every config struct.
pub trait Config: Sized {
    type Toml: Default + for<'de> serde::Deserialize<'de>;
    type Args: clap::Args + zbobr_utility::PrefixedArgs + Default + Clone;
    fn build(toml: Option<Self::Toml>, args: Self::Args, config_dir: &std::path::Path) -> Self;
}

/// Configuration for the zbobr dispatcher.
#[derive(Clone)]
#[config_struct]
pub struct ZbobrDispatcherConfig {
    /// Workspaces directory; each task gets a separate subdirectory.
    #[config(path)]
    pub workspaces: std::path::PathBuf,
    /// Base port for the MCP server; zbobr scans upward from this port to find
    /// an available one.
    #[arg(default_value = "3000")]
    pub base_port: u16,
    /// Read-only GitHub token passed as GH_TOKEN/GITHUB_TOKEN to agent processes.
    /// This is a security boundary: it limits what agents can do on GitHub — agents must
    /// not have write access so that erroneous or misbehaving agents cannot modify remote
    /// repositories. Use a fine-grained token with read-only scopes (or no scopes at all
    /// for fully offline/mcp-tester runs). Defaults to "not-configured" when omitted.
    pub agent_github_token: String,
    /// CLI tool to use as a global default. Individual stages may override this.
    pub tool: Tool,
    /// Global AI model to use when a stage does not specify an override.  Returns
    /// to `Model::default()` when omitted so existing configurations keep working.
    /// Individual stages may still specify their own model, which takes precedence.
    pub model: Model,

    /// Default configuration for the preparator stage.
    #[config(nested)]
    pub preparator: StageConfig,
    /// Default configuration for the planner stage.
    #[config(nested)]
    pub planner: StageConfig,
    /// Default configuration for the worker stage.
    #[config(nested)]
    pub worker: StageConfig,
    /// Default configuration for the reviewer stage.
    #[config(nested)]
    pub reviewer: StageConfig,
    /// Default configuration for the tester stage.
    #[config(nested)]
    pub tester: StageConfig,
    /// Default configuration for the merger stage.
    #[config(nested)]
    pub merger: StageConfig,
    /// Prefix for work branches (default: "zbobr_fix").
    pub work_branch_prefix: String,
    /// Default destination repository pre-populated into task parameters before the
    /// preparator agent runs (e.g. "owner/repo" or a full git URL). The preparator
    /// may still override this value. When unset the agent must determine the
    /// repository from the task description alone.
    pub default_destination_repository: Option<String>,
    /// Default destination branch pre-populated into task parameters before the
    /// preparator agent runs (e.g. "main"). The preparator may still override this.
    pub default_destination_branch: Option<String>,
}

impl Default for ZbobrDispatcherConfig {
    fn default() -> Self {
        Self {
            workspaces: std::path::PathBuf::from("./workspaces"),
            base_port: 3000,
            agent_github_token: "not-configured".to_string(),
            tool: Tool::default(),
            model: Model::default(),
            preparator: StageConfig::default(),
            planner: StageConfig::default(),
            worker: StageConfig::default(),
            reviewer: StageConfig::default(),
            tester: StageConfig::default(),
            merger: StageConfig::default(),
            work_branch_prefix: "zbobr_fix".to_string(),
            default_destination_repository: None,
            default_destination_branch: None,
        }
    }
}

// Note: zbobr-specific env helpers were removed — configuration now comes
// from TOML/CLI or explicit external GH env vars. `EnvSource` provides an
// abstraction for reading environment variables in tests.

impl ZbobrDispatcherConfig {
    /// Load configuration from environment variables only (backward compat).
    pub fn from_env() -> anyhow::Result<Self> {
        let cwd = std::env::current_dir()
            .map_err(|e| anyhow::anyhow!("Cannot get current directory: {e}"))?;
        Ok(<Self as Config>::build(
            None,
            ZbobrDispatcherArgs::default(),
            &cwd,
        ))
    }

    /// Validate that all required fields are set.
    pub fn validate(&self) -> anyhow::Result<()> {
        // global tool/model compatibility
        if self.model.model_name_for_tool(self.tool).is_none() {
            anyhow::bail!(
                "Global model {:?} is not supported by global tool {:?}",
                self.model,
                self.tool
            );
        }

        // check every role-specific combination (including overrides)
        for role in &[
            crate::task::Role::Preparator,
            crate::task::Role::Planner,
            crate::task::Role::Worker,
            crate::task::Role::Reviewer,
            crate::task::Role::Tester,
            crate::task::Role::Merger,
        ] {
            let tool = self.tool_for_role(*role);
            let model = self.model_for_role(*role);
            if model.model_name_for_tool(tool).is_none() {
                anyhow::bail!(
                    "Configured model {:?} is not supported by tool {:?} for role {:?}",
                    model,
                    tool,
                    role
                );
            }
        }

        Ok(())
    }

    /// Lookup the stage configuration associated with a given role.  These
    /// are stored separately for each stage so that owner can customize each
    /// phase of the workflow independently.
    pub fn stage_for_role(&self, role: crate::task::Role) -> &StageConfig {
        match role {
            crate::task::Role::Preparator => &self.preparator,
            crate::task::Role::Planner => &self.planner,
            crate::task::Role::Worker => &self.worker,
            crate::task::Role::Reviewer => &self.reviewer,
            crate::task::Role::Tester => &self.tester,
            crate::task::Role::Merger => &self.merger,
        }
    }

    /// Determine which tool should be used for the given role, falling back
    /// to the global `cli_tool` setting if the stage does not specify one.
    pub fn tool_for_role(&self, role: crate::task::Role) -> crate::task::Tool {
        self.stage_for_role(role).tool.unwrap_or(self.tool)
    }

    /// Determine which model should be used for the given role.  The precedence
    /// order is: stage-specific override, then the global dispatcher `model`.
    /// The result is _never_ optional; a default value is provided by
    /// `Model::default()` so callers can apply it unconditionally.
    pub fn model_for_role(&self, role: crate::task::Role) -> crate::task::Model {
        self.stage_for_role(role)
            .model
            .clone()
            .unwrap_or(self.model.clone())
    }
}
