use std::{collections::HashMap, path::PathBuf};

use indexmap::IndexMap;
use zbobr_utility::config_struct;

use crate::{config_tools::McpTool, task::{Model, Pipeline, Stage, Tool}};
use zbobr_utility::Secret;

/// Auto-generated by #[config_struct] for every config struct.
pub trait Config: Sized {
    type Toml: Default + for<'de> serde::Deserialize<'de>;
    type Args: clap::Args + zbobr_utility::PrefixedArgs + Default + Clone;
    fn build(toml: Option<Self::Toml>, args: Self::Args, config_dir: &std::path::Path) -> Self;
}

/// Definition of a role: which MCP tools it can access, an optional prompt file, and optional tool override.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Default)]
#[serde(deny_unknown_fields)]
pub struct RoleDefinition {
    pub mcp: Vec<McpTool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<PathBuf>,
    /// Tool name override for this role. Overrides the global dispatcher `tool`.
    /// Stage-level `tool` takes precedence over this.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
}

/// A provider definition: a named executor configuration with optional inheritance.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct ProviderDefinition {
    /// Executor type (e.g. "claude", "copilot", "mcp-tester").
    /// Required unless `parent` is set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor: Option<String>,
    /// Parent provider to inherit settings from. Child fields override parent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// Selection priority. Higher values are preferred. Omit to inherit from
    /// parent (root providers default to 10).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// Enable plan mode for this provider. Overrides any executor default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_mode: Option<bool>,
    /// API key for the executor (e.g. Anthropic API key for the claude executor).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access_key: Option<Secret>,
}


/// A resolved provider with all inheritance fully flattened.
#[derive(Clone, Debug)]
pub struct ResolvedProvider {
    pub name: String,
    pub executor: String,
    pub priority: i32,
    pub plan_mode: bool,
    pub access_key: Option<Secret>,
}

/// One entry within a named tool definition: a (provider, model) pair.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct ToolEntry {
    pub provider: String,
    pub model: Model,
}

/// A stage transition descriptor with an optional target stage and pause flag.
///
/// Accepts two TOML forms:
/// - String shorthand: `on_success = "stage_b"` → `{ next: Some("stage_b"), pause: false }`
/// - Full table: `on_success = { next = "stage_b", pause = true }`
///
/// Both `next` and `pause` are optional (defaults: `None` and `false`).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize)]
pub struct StageTransition {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<Stage>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub pause: bool,
}

impl StageTransition {
    pub fn stage(next: impl Into<Stage>) -> Self {
        Self {
            next: Some(next.into()),
            pause: false,
        }
    }

    pub fn pause() -> Self {
        Self {
            next: None,
            pause: true,
        }
    }
}

impl<'de> serde::Deserialize<'de> for StageTransition {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(serde::Deserialize)]
        #[serde(deny_unknown_fields)]
        struct FullTransition {
            #[serde(default)]
            next: Option<Stage>,
            #[serde(default)]
            pause: bool,
        }
        #[derive(serde::Deserialize)]
        #[serde(untagged)]
        enum Helper {
            Stage(Stage),
            Full(FullTransition),
        }
        match Helper::deserialize(deserializer)? {
            Helper::Stage(s) => Ok(StageTransition {
                next: Some(s),
                pause: false,
            }),
            Helper::Full(f) => Ok(StageTransition {
                next: f.next,
                pause: f.pause,
            }),
        }
    }
}

/// A single stage in the configurable pipeline.
///
/// The stage's name and pipeline are derived from its structural position
/// (key in the stages HashMap and key in the pipelines HashMap).
///
/// A stage must have exactly one of `role` (run an agent session) or
/// `call` (call another pipeline). They are mutually exclusive.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Default)]
#[serde(deny_unknown_fields)]
pub struct StageDefinition {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call: Option<Pipeline>,
    /// Tool name override for this stage. Overrides role-level and global `tool`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_prompt: Option<PathBuf>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub prompts: Vec<PathBuf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_success: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_failure: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_intermediate: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_no_report: Option<StageTransition>,
}

impl StageDefinition {
    pub fn role_name(&self) -> Option<&str> {
        self.role.as_deref()
    }

    pub fn call_pipeline(&self) -> Option<&Pipeline> {
        self.call.as_ref()
    }

    pub fn is_call(&self) -> bool {
        self.call.is_some()
    }

    pub fn on_success(&self) -> Option<&StageTransition> {
        self.on_success.as_ref()
    }

    pub fn on_failure(&self) -> Option<&StageTransition> {
        self.on_failure.as_ref()
    }

    pub fn on_intermediate(&self) -> Option<&StageTransition> {
        self.on_intermediate.as_ref()
    }

    pub fn on_no_report(&self) -> Option<&StageTransition> {
        self.on_no_report.as_ref()
    }
}

/// Per-pipeline configuration: an ordered sequence of stages.
///
/// Stage order is determined by insertion order in the `IndexMap`.
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct PipelineConfig {
    #[serde(default)]
    pub stages: IndexMap<Stage, StageDefinition>,
}

impl PipelineConfig {
    /// Look up a stage by name.
    pub fn stage(&self, name: &str) -> Option<&StageDefinition> {
        self.stages.get(name)
    }

    /// Get the index of a stage in the order.
    pub fn stage_index(&self, name: &str) -> Option<usize> {
        self.stages.get_index_of(name)
    }

    /// Get the next stage after `name`.
    pub fn next_stage(&self, name: &str) -> Option<(&str, &StageDefinition)> {
        let idx = self.stages.get_index_of(name)?;
        let (next_name, def) = self.stages.get_index(idx + 1)?;
        Some((next_name.as_str(), def))
    }

    /// Get the first stage of this pipeline.
    pub fn first_stage(&self) -> Option<(&str, &StageDefinition)> {
        let (name, def) = self.stages.first()?;
        Some((name.as_str(), def))
    }

    /// Get the start stage for this pipeline (delegates to first_stage).
    pub fn start_stage(&self) -> Option<(&str, &StageDefinition)> {
        self.first_stage()
    }

    /// Validate pipeline configuration.
    pub fn validate(&self, pipeline_name: &str) -> anyhow::Result<()> {
        if self.stages.is_empty() {
            anyhow::bail!("Pipeline '{}' has no stages", pipeline_name);
        }
        for (sname, stage) in &self.stages {
            match (&stage.role, &stage.call) {
                (Some(_), Some(_)) => anyhow::bail!(
                    "Pipeline '{}' stage '{}' has both 'role' and 'call' — only one is allowed",
                    pipeline_name,
                    sname
                ),
                (None, None) => anyhow::bail!(
                    "Pipeline '{}' stage '{}' has neither 'role' nor 'call' — one is required",
                    pipeline_name,
                    sname
                ),
                _ => {}
            }
            if let Some(ref target) = stage.on_success.as_ref().and_then(|t| t.next.as_ref()) {
                if !self.stages.contains_key(target.as_str()) {
                    anyhow::bail!(
                        "Pipeline '{}' stage '{}' on_success references unknown stage '{}'",
                        pipeline_name,
                        sname,
                        target
                    );
                }
            }
            if let Some(ref target) = stage.on_failure.as_ref().and_then(|t| t.next.as_ref()) {
                if !self.stages.contains_key(target.as_str()) {
                    anyhow::bail!(
                        "Pipeline '{}' stage '{}' on_failure references unknown stage '{}'",
                        pipeline_name,
                        sname,
                        target
                    );
                }
            }
            if let Some(ref target) = stage.on_intermediate.as_ref().and_then(|t| t.next.as_ref()) {
                if !self.stages.contains_key(target.as_str()) {
                    anyhow::bail!(
                        "Pipeline '{}' stage '{}' on_intermediate references unknown stage '{}'",
                        pipeline_name,
                        sname,
                        target
                    );
                }
            }
        }
        Ok(())
    }
}

/// Top-level workflow configuration: a container of named pipelines and shared roles.
///
/// Defined manually (not via `#[config_struct]`) because it needs
/// custom `Config` impl with `WorkflowArgs` / `WorkflowToml`.
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowConfig {
    /// Base directory for prompt files; prepended to relative prompt paths.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompts_dir: Option<PathBuf>,
    #[serde(default)]
    pub roles: IndexMap<String, RoleDefinition>,
    #[serde(default)]
    pub pipelines: HashMap<Pipeline, PipelineConfig>,
}

/// TOML representation of WorkflowConfig (all fields optional).
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowToml {
    #[serde(default)]
    pub prompts_dir: Option<PathBuf>,
    #[serde(default)]
    pub roles: Option<IndexMap<String, RoleDefinition>>,
    #[serde(default)]
    pub pipelines: Option<HashMap<Pipeline, PipelineConfig>>,
}

/// CLI arguments for WorkflowConfig (empty — no CLI-overridable fields).
#[derive(Clone, Debug, Default)]
pub struct WorkflowArgs;

impl clap::Args for WorkflowArgs {
    fn augment_args(cmd: clap::Command) -> clap::Command {
        cmd
    }
    fn augment_args_for_update(cmd: clap::Command) -> clap::Command {
        cmd
    }
}

impl clap::FromArgMatches for WorkflowArgs {
    fn from_arg_matches(_matches: &clap::ArgMatches) -> Result<Self, clap::Error> {
        Ok(WorkflowArgs)
    }
    fn update_from_arg_matches(&mut self, _matches: &clap::ArgMatches) -> Result<(), clap::Error> {
        Ok(())
    }
}

impl zbobr_utility::PrefixedArgs for WorkflowArgs {
    fn augment_args_prefixed(cmd: clap::Command, _prefix: &str) -> clap::Command {
        cmd
    }
    fn from_matches_prefixed(
        _matches: &clap::ArgMatches,
        _prefix: &str,
    ) -> Result<Self, clap::Error> {
        Ok(WorkflowArgs)
    }
}

impl WorkflowArgs {
    pub fn has_overrides(&self) -> bool {
        false
    }
}

impl WorkflowToml {
    pub fn merge_with_args(self, _args: WorkflowArgs) -> Self {
        self
    }

    pub fn try_into_config(self) -> anyhow::Result<WorkflowConfig> {
        Ok(WorkflowConfig {
            prompts_dir: self.prompts_dir,
            roles: self.roles.unwrap_or_default(),
            pipelines: self.pipelines.unwrap_or_default(),
        })
    }
}

impl Config for WorkflowConfig {
    type Toml = WorkflowToml;
    type Args = WorkflowArgs;

    fn build(toml: Option<Self::Toml>, _args: Self::Args, _config_dir: &std::path::Path) -> Self {
        match toml {
            Some(t) => WorkflowConfig {
                prompts_dir: t.prompts_dir,
                roles: t.roles.unwrap_or_default(),
                pipelines: t.pipelines.unwrap_or_default(),
            },
            None => WorkflowConfig::default(),
        }
    }
}

impl WorkflowConfig {
    /// Look up a pipeline by name.
    pub fn pipeline(&self, name: impl Into<Pipeline>) -> Option<&PipelineConfig> {
        self.pipelines.get(name.into().as_str())
    }

    /// Look up a stage in a specific pipeline.
    pub fn stage(&self, pipeline: impl Into<Pipeline>, stage: &str) -> Option<&StageDefinition> {
        self.pipelines.get(pipeline.into().as_str())?.stage(stage)
    }

    /// Get the start stage for a pipeline.
    pub fn start_stage_for_pipeline(
        &self,
        pipeline: impl Into<Pipeline>,
    ) -> Option<(&str, &StageDefinition)> {
        self.pipelines.get(pipeline.into().as_str())?.start_stage()
    }

    /// The default pipeline name.
    pub fn default_pipeline(&self) -> Pipeline {
        Pipeline::Main
    }

    /// All pipeline names.
    pub fn pipeline_names(&self) -> Vec<&Pipeline> {
        let mut names: Vec<&Pipeline> = self.pipelines.keys().collect();
        names.sort();
        names
    }

    /// Find the first stage with a given role (across all pipelines, preferring default pipeline).
    pub fn find_stage_by_role(&self, role: &str) -> Option<(&Pipeline, &str, &StageDefinition)> {
        let default = self.default_pipeline();
        if let Some(pipeline) = self.pipelines.get(default.as_str()) {
            if let Some((name, stage)) = pipeline
                .stages
                .iter()
                .find(|(_, s)| s.role_name() == Some(role))
            {
                return self
                    .pipelines
                    .get_key_value(default.as_str())
                    .map(|(p, _)| (p, name.as_str(), stage));
            }
        }
        for (pname, pipeline) in &self.pipelines {
            if let Some((sname, stage)) = pipeline
                .stages
                .iter()
                .find(|(_, s)| s.role_name() == Some(role))
            {
                return Some((pname, sname.as_str(), stage));
            }
        }
        None
    }

    /// Look up a role definition by name.
    pub fn role_definition(&self, role: &str) -> Option<&RoleDefinition> {
        self.roles.get(role)
    }

    /// Iterate over all stages as `(pipeline_name, stage_name, &StageDefinition)` tuples.
    pub fn all_stages(&self) -> Vec<(&Pipeline, &str, &StageDefinition)> {
        let mut result = Vec::new();
        for (pname, pipeline) in &self.pipelines {
            for (sname, stage) in &pipeline.stages {
                result.push((pname, sname.as_str(), stage));
            }
        }
        result
    }

    /// All static tool names.
    pub fn all_tool_names(&self) -> Vec<String> {
        McpTool::all().iter().map(|t| t.to_string()).collect()
    }

    /// Validate the entire workflow configuration.
    pub fn validate(&self) -> anyhow::Result<()> {
        // Required pipelines must exist
        for required in [Pipeline::Main, Pipeline::Merge] {
            if !self.pipelines.contains_key(required.as_str()) {
                anyhow::bail!(
                    "Required pipeline '{}' is missing from [workflow.pipelines]",
                    required
                );
            }
        }

        let pipeline_names = self.pipeline_names();

        // Each pipeline must have valid order/stages
        for pname in &pipeline_names {
            let pipeline = self.pipelines.get(pname.as_str()).unwrap();
            pipeline.validate(pname.as_str())?;
        }

        // Every role-stage's role must exist in the roles map (if roles are configured)
        if !self.roles.is_empty() {
            for (pname, pipeline) in &self.pipelines {
                for (sname, stage) in &pipeline.stages {
                    if let Some(role) = &stage.role {
                        if !self.roles.contains_key(role) {
                            anyhow::bail!(
                                "Stage '{}/{}' references unknown role '{}' (not in [workflow.roles])",
                                pname,
                                sname,
                                role
                            );
                        }
                    }
                }
            }
        }

        // Every call-stage's target pipeline must exist
        for (pname, pipeline) in &self.pipelines {
            for (sname, stage) in &pipeline.stages {
                if let Some(target) = &stage.call {
                    if !self.pipelines.contains_key(target.as_str()) {
                        anyhow::bail!(
                            "Stage '{}/{}' calls unknown pipeline '{}'",
                            pname,
                            sname,
                            target
                        );
                    }
                }
            }
        }

        Ok(())
    }
}

/// Configuration for the zbobr dispatcher.
#[derive(Clone)]
#[config_struct]
pub struct ZbobrDispatcherConfig {
    /// Name of this zbobr instance. Used to label tasks (zbobr:<instance>) so that
    /// multiple instances can run against the same repository without interfering.
    pub instance: String,
    /// Workspaces directory; each task gets a separate subdirectory.
    #[config(path)]
    pub workspaces: std::path::PathBuf,
    /// Base port for the MCP server; zbobr scans upward from this port to find
    /// an available one.
    #[arg(default_value = "3000")]
    pub base_port: u16,
    /// Read-only GitHub token passed as GH_TOKEN/GITHUB_TOKEN to agent processes.
    /// This is a security boundary: it limits what agents can do on GitHub — agents must
    /// not have write access so that erroneous or misbehaving agents cannot modify remote
    /// repositories. Use a fine-grained token with read-only scopes (or no scopes at all
    /// for fully offline/mcp-tester runs). Defaults to `{ value = "not-configured" }` when omitted.
    /// Use `{ value = "token" }` for an inline token or `{ env = "VAR" }` to read from an env var.
    #[config(skip_args)]
    pub agent_github_token: Secret,
    /// Global default tool name. Stages and roles may override this.
    pub tool: String,
    /// Named provider definitions. Providers map a name to an executor + settings.
    #[config(skip_args)]
    pub providers: IndexMap<String, ProviderDefinition>,
    /// Named tool definitions. Each tool is a list of (provider, model) pairs.
    #[config(skip_args)]
    pub tools: IndexMap<String, Vec<ToolEntry>>,
    /// Seconds a provider is excluded from selection after a failure.
    #[config(skip_args)]
    pub provider_exclusion_secs: u64,
    /// Prefix for work branches (default: "zbobr_fix").
    pub work_branch_prefix: String,
    /// Git user name for commits made by the tool.
    pub git_user_name: String,
    /// Git user email for commits made by the tool.
    pub git_user_email: String,
    /// Rewrite commit authors after each stage completes to match configured git user.
    pub overwrite_author: bool,
    /// Maximum number of stages a task is allowed to pass before being auto-paused.
    /// When a task's stage_count reaches this limit, the task is paused automatically.
    /// Set to 0 to disable the limit. Default: 20.
    #[arg(default_value = "20")]
    pub max_task_stage_count: u64,
    /// Timezone for timestamps (e.g. "+0300", "-0500", "+03:00").
    /// If not set, the operating system's local timezone is used.
    pub timezone: Option<crate::task::FixedOffsetTz>,
}

impl Default for ZbobrDispatcherConfig {
    fn default() -> Self {
        Self {
            instance: "default".to_string(),
            workspaces: std::path::PathBuf::from("./workspaces"),
            base_port: 3000,
            agent_github_token: Secret::value("not-configured"),
            tool: "smart".to_string(),
            providers: IndexMap::new(),
            tools: IndexMap::new(),
            provider_exclusion_secs: 300,
            work_branch_prefix: "zbobr_fix".to_string(),
            git_user_name: String::new(),
            git_user_email: String::new(),
            overwrite_author: false,
            max_task_stage_count: 20,
            timezone: None,
        }
    }
}

impl ZbobrDispatcherConfig {
    /// Load configuration from environment variables only (backward compat).
    pub fn from_env() -> anyhow::Result<Self> {
        let cwd = std::env::current_dir()
            .map_err(|e| anyhow::anyhow!("Cannot get current directory: {e}"))?;
        Ok(<Self as Config>::build(
            None,
            ZbobrDispatcherArgs::default(),
            &cwd,
        ))
    }

    /// Returns the configured timezone offset, or the system's local timezone if not set.
    pub fn fixed_offset(&self) -> chrono::FixedOffset {
        match &self.timezone {
            Some(tz) => **tz,
            None => *chrono::Local::now().offset(),
        }
    }

    /// Validate configuration consistency and resolve all secrets.
    pub fn validate(&mut self) -> anyhow::Result<()> {
        // Verify parent references are valid
        for (provider_name, provider) in &self.providers {
            if let Some(ref parent) = provider.parent {
                if !self.providers.contains_key(parent.as_str()) {
                    anyhow::bail!(
                        "Provider '{}' references unknown parent '{}'",
                        provider_name,
                        parent
                    );
                }
            }
            if provider.executor.is_none() && provider.parent.is_none() {
                anyhow::bail!(
                    "Provider '{}' has neither 'executor' nor 'parent' — one is required",
                    provider_name
                );
            }
            if let Some(ref executor) = provider.executor {
                let valid = [Tool::CLAUDE, Tool::COPILOT, Tool::MCP_TESTER];
                if !valid.contains(&executor.as_str()) {
                    anyhow::bail!(
                        "Provider '{}' has unknown executor '{}' — must be one of 'claude', 'copilot', 'mcp-tester'",
                        provider_name,
                        executor
                    );
                }
            }
        }
        // Verify tool entries reference existing providers
        for (tool_name, entries) in &self.tools {
            for entry in entries {
                if !self.providers.contains_key(entry.provider.as_str()) {
                    anyhow::bail!(
                        "Tool '{}' references unknown provider '{}'",
                        tool_name,
                        entry.provider
                    );
                }
            }
        }
        // Verify global default tool name exists
        if !self.tools.is_empty() && !self.tools.contains_key(self.tool.as_str()) {
            anyhow::bail!(
                "Global dispatcher tool '{}' is not defined in [tools]",
                self.tool
            );
        }
        self.agent_github_token.resolve()?;
        // Resolve secrets in providers
        for provider in self.providers.values_mut() {
            if let Some(ref mut key) = provider.access_key {
                key.resolve()?;
            }
        }
        Ok(())
    }

    /// Validate that all tool-name references in role and stage definitions exist in `self.tools`.
    pub fn validate_workflow_refs(&self, workflow: &WorkflowConfig) -> anyhow::Result<()> {
        for (role_name, role_def) in &workflow.roles {
            if let Some(ref tool) = role_def.tool {
                if !self.tools.contains_key(tool.as_str()) {
                    anyhow::bail!(
                        "Role '{}' references unknown tool '{}' (not in [tools])",
                        role_name,
                        tool
                    );
                }
            }
        }
        for (pname, pipeline) in &workflow.pipelines {
            for (sname, stage) in &pipeline.stages {
                if let Some(ref tool) = stage.tool {
                    if !self.tools.contains_key(tool.as_str()) {
                        anyhow::bail!(
                            "Stage '{}/{}' references unknown tool '{}' (not in [tools])",
                            pname,
                            sname,
                            tool
                        );
                    }
                }
            }
        }
        Ok(())
    }

    /// Determine the effective tool name for a stage.
    ///
    /// Precedence: stage.tool → role.tool → global dispatcher.tool
    pub fn resolve_tool_name(&self, stage_def: &StageDefinition, workflow: &WorkflowConfig) -> String {
        if let Some(ref tool) = stage_def.tool {
            return tool.clone();
        }
        if let Some(role_name) = stage_def.role_name() {
            if let Some(role_def) = workflow.role_definition(role_name) {
                if let Some(ref tool) = role_def.tool {
                    return tool.clone();
                }
            }
        }
        self.tool.clone()
    }

    /// Resolve all providers by flattening inheritance chains.
    ///
    /// Returns an `IndexMap` from provider name to `ResolvedProvider`.
    pub fn resolve_providers(&self) -> anyhow::Result<IndexMap<String, ResolvedProvider>> {
        let mut resolved = IndexMap::new();
        for name in self.providers.keys() {
            let rp = self.resolve_single_provider(name, &mut Vec::new())?;
            resolved.insert(name.clone(), rp);
        }
        Ok(resolved)
    }

    fn resolve_single_provider(
        &self,
        name: &str,
        visited: &mut Vec<String>,
    ) -> anyhow::Result<ResolvedProvider> {
        if visited.contains(&name.to_string()) {
            anyhow::bail!("Circular parent reference detected in provider '{}'", name);
        }
        visited.push(name.to_string());

        let def = self
            .providers
            .get(name)
            .ok_or_else(|| anyhow::anyhow!("Provider '{}' not found", name))?;

        if let Some(ref parent_name) = def.parent {
            let parent = self.resolve_single_provider(parent_name, visited)?;
            Ok(ResolvedProvider {
                name: name.to_string(),
                executor: def.executor.clone().unwrap_or(parent.executor),
                priority: def.priority.unwrap_or(parent.priority),
                plan_mode: def.plan_mode.unwrap_or(parent.plan_mode),
                access_key: def.access_key.clone().or(parent.access_key),
            })
        } else {
            let executor = def.executor.clone().ok_or_else(|| {
                anyhow::anyhow!(
                    "Provider '{}' has no executor and no parent",
                    name
                )
            })?;
            Ok(ResolvedProvider {
                name: name.to_string(),
                executor,
                priority: def.priority.unwrap_or(10),
                plan_mode: def.plan_mode.unwrap_or(false),
                access_key: def.access_key.clone(),
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use indexmap::IndexMap;

    /// Helper: build a minimal ZbobrDispatcherConfig with given providers and tools.
    fn make_config(
        providers: IndexMap<String, ProviderDefinition>,
        tools: IndexMap<String, Vec<ToolEntry>>,
    ) -> ZbobrDispatcherConfig {
        ZbobrDispatcherConfig {
            providers,
            tools,
            ..Default::default()
        }
    }

    // ── resolve_providers tests ──────────────────────────────────────────

    #[test]
    fn resolve_providers_basic() {
        let mut providers = IndexMap::new();
        providers.insert(
            "claude".to_string(),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        assert_eq!(resolved.len(), 1);
        let rp = &resolved["claude"];
        assert_eq!(rp.name, "claude");
        assert_eq!(rp.executor, "claude");
        assert_eq!(rp.priority, 10);
        assert!(!rp.plan_mode);
        assert!(rp.access_key.is_none());
    }

    #[test]
    fn resolve_providers_single_level_inheritance() {
        let mut providers = IndexMap::new();
        providers.insert(
            "claude_base".to_string(),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(
            "claude_child".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("claude_base".to_string()),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved["claude_child"];
        assert_eq!(child.executor, "claude");
    }

    #[test]
    fn resolve_providers_multi_level_chain() {
        let mut providers = IndexMap::new();
        providers.insert(
            "grandparent".to_string(),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(
            "parent".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("grandparent".to_string()),
                priority: None,
                plan_mode: Some(true),
                access_key: None,
            },
        );
        providers.insert(
            "child".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("parent".to_string()),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved["child"];
        assert_eq!(child.executor, "claude");
        assert!(child.plan_mode);
    }

    #[test]
    fn resolve_providers_circular_reference() {
        let mut providers = IndexMap::new();
        providers.insert(
            "a".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("b".to_string()),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(
            "b".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("a".to_string()),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let err = config.resolve_providers().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(msg.contains("circular"), "Expected 'circular' in error: {msg}");
    }

    #[test]
    fn resolve_providers_child_overrides_parent() {
        let mut providers = IndexMap::new();
        providers.insert(
            "base".to_string(),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: Some(false),
                access_key: None,
            },
        );
        providers.insert(
            "child".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("base".to_string()),
                priority: Some(5),
                plan_mode: Some(true),
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved["child"];
        assert_eq!(child.executor, "claude");
        assert_eq!(child.priority, 5);
        assert!(child.plan_mode);
    }

    // ── validate tests ──────────────────────────────────────────────────

    #[test]
    fn validate_valid_config() {
        let mut providers = IndexMap::new();
        providers.insert(
            "claude".to_string(),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert(
            "smart".to_string(),
            vec![ToolEntry {
                provider: "claude".to_string(),
                model: "opus".parse().unwrap(),
            }],
        );
        let mut config = make_config(providers, tools);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn validate_unknown_parent() {
        let mut providers = IndexMap::new();
        providers.insert(
            "child".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("nonexistent".to_string()),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut config = make_config(providers, IndexMap::new());
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("unknown parent"),
            "Expected 'unknown parent' in error: {msg}"
        );
    }

    #[test]
    fn validate_no_executor_no_parent() {
        let mut providers = IndexMap::new();
        providers.insert(
            "broken".to_string(),
            ProviderDefinition {
                executor: None,
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut config = make_config(providers, IndexMap::new());
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("neither 'executor' nor 'parent'"),
            "Expected \"neither 'executor' nor 'parent'\" in error: {msg}"
        );
    }

    #[test]
    fn validate_tool_references_unknown_provider() {
        let mut providers = IndexMap::new();
        providers.insert(
            "claude".to_string(),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert(
            "smart".to_string(),
            vec![ToolEntry {
                provider: "ghost".to_string(),
                model: "opus".parse().unwrap(),
            }],
        );
        let mut config = make_config(providers, tools);
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("unknown provider"),
            "Expected 'unknown provider' in error: {msg}"
        );
    }

    // ── resolve_tool_name tests ─────────────────────────────────────────

    fn make_workflow_with_role(role_name: &str, tool: Option<String>) -> WorkflowConfig {
        let mut roles = IndexMap::new();
        roles.insert(
            role_name.to_string(),
            RoleDefinition {
                mcp: vec![],
                prompt: None,
                tool,
            },
        );
        WorkflowConfig {
            prompts_dir: None,
            roles,
            pipelines: HashMap::new(),
        }
    }

    #[test]
    fn resolve_tool_name_stage_overrides() {
        let stage = StageDefinition {
            tool: Some("stage-tool".to_string()),
            role: Some("worker".to_string()),
            ..Default::default()
        };
        let workflow = make_workflow_with_role("worker", Some("role-tool".to_string()));
        let config = ZbobrDispatcherConfig {
            tool: "global-tool".to_string(),
            ..Default::default()
        };
        assert_eq!(config.resolve_tool_name(&stage, &workflow), "stage-tool");
    }

    #[test]
    fn resolve_tool_name_falls_back_to_role() {
        let stage = StageDefinition {
            tool: None,
            role: Some("worker".to_string()),
            ..Default::default()
        };
        let workflow = make_workflow_with_role("worker", Some("role-tool".to_string()));
        let config = ZbobrDispatcherConfig {
            tool: "global-tool".to_string(),
            ..Default::default()
        };
        assert_eq!(config.resolve_tool_name(&stage, &workflow), "role-tool");
    }

    #[test]
    fn resolve_tool_name_falls_back_to_global() {
        let stage = StageDefinition {
            tool: None,
            role: Some("worker".to_string()),
            ..Default::default()
        };
        let workflow = make_workflow_with_role("worker", None);
        let config = ZbobrDispatcherConfig {
            tool: "global-tool".to_string(),
            ..Default::default()
        };
        assert_eq!(config.resolve_tool_name(&stage, &workflow), "global-tool");
    }

    #[test]
    fn resolve_tool_name_no_role_falls_back_to_global() {
        let stage = StageDefinition {
            tool: None,
            role: Some("nonexistent".to_string()),
            ..Default::default()
        };
        let workflow = WorkflowConfig::default();
        let config = ZbobrDispatcherConfig {
            tool: "global-tool".to_string(),
            ..Default::default()
        };
        assert_eq!(config.resolve_tool_name(&stage, &workflow), "global-tool");
    }

    // ── resolve_providers – priority inheritance ────────────────────────

    #[test]
    fn resolve_providers_inherits_priority_from_parent() {
        let mut providers = IndexMap::new();
        providers.insert(
            "base".to_string(),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: Some(3),
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(
            "child".to_string(),
            ProviderDefinition {
                executor: None,
                parent: Some("base".to_string()),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved["child"];
        assert_eq!(
            child.priority, 3,
            "Child should inherit parent's priority (3), not default (10)"
        );
    }

    // ── validate – unknown executor ─────────────────────────────────────

    #[test]
    fn validate_unknown_executor() {
        let mut providers = IndexMap::new();
        providers.insert(
            "bad".to_string(),
            ProviderDefinition {
                executor: Some("invalid_executor".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut config = make_config(providers, IndexMap::new());
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("unknown executor"),
            "Expected 'unknown executor' in error: {msg}"
        );
    }
}
