[package]
name = "zbobr-executor-mcp-tester"
version = "0.1.0"
edition = "2024"

[dependencies]
zbobr-api = { workspace = true }
zbobr-utility = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
paste = { workspace = true }
