use std::path::PathBuf;

use crate::{
    config::{ZbobrDispatcherArgs, ZbobrDispatcherConfig},
    task::Role,
    ZbobrDispatcher,
};

use zbobr_api::Task;

/// Resolved prompt file paths for each role.
#[derive(Debug, Clone)]
pub struct Prompts {
    pub base_path: Option<PathBuf>,
    pub preparator: Vec<PathBuf>,
    pub planner: Vec<PathBuf>,
    pub worker: Vec<PathBuf>,
    pub reviewer: Vec<PathBuf>,
    pub tester: Vec<PathBuf>,
    pub merger: Vec<PathBuf>,
}

/// Resolve prompt paths from CLI args and config.
/// CLI args take precedence over config values.
pub fn resolve_prompts(args: &ZbobrDispatcherArgs, config: &ZbobrDispatcherConfig) -> Prompts {
    // CLI flags still use the old per-role names; they override whatever is in
    // the stage config.  If neither CLI nor stage config provides values we
    // simply return an empty vector.
    // args now has a nested `preparator`, `planner`, etc. field generated by
    // the config_struct macro (each of type StageConfigArgs).  Those nested
    // structs expose an optional `prompts` member matching the TOML value.
    let preparator = args
        .preparator
        .prompts
        .clone()
        .unwrap_or_else(|| config.preparator.prompts.clone());
    let planner = args
        .planner
        .prompts
        .clone()
        .unwrap_or_else(|| config.planner.prompts.clone());
    let worker = args
        .worker
        .prompts
        .clone()
        .unwrap_or_else(|| config.worker.prompts.clone());
    let reviewer = args
        .reviewer
        .prompts
        .clone()
        .unwrap_or_else(|| config.reviewer.prompts.clone());
    let tester = args
        .tester
        .prompts
        .clone()
        .unwrap_or_else(|| config.tester.prompts.clone());
    let merger = args
        .merger
        .prompts
        .clone()
        .unwrap_or_else(|| config.merger.prompts.clone());
    let base_path = args
        .prompts_path
        .clone()
        .or_else(|| config.prompts_path.clone());

    Prompts {
        base_path,
        preparator,
        planner,
        worker,
        reviewer,
        tester,
        merger,
    }
}

/// Load and concatenate multiple prompt files.
/// Relative paths are resolved relative to `base_path` if provided, otherwise cwd.
/// Returns an error if any file cannot be read.
pub fn load_prompts(paths: &[PathBuf], base_path: Option<&PathBuf>) -> anyhow::Result<String> {
    let mut combined = String::new();
    for path in paths.iter() {
        let resolved_path = if let Some(base) = base_path {
            if path.is_relative() {
                base.join(path)
            } else {
                path.clone()
            }
        } else if path.is_relative() {
            std::env::current_dir()?.join(path)
        } else {
            path.clone()
        };

        let content = std::fs::read_to_string(&resolved_path).map_err(|e| {
            anyhow::anyhow!(
                "Failed to read prompt file '{}': {}",
                resolved_path.display(),
                e
            )
        })?;

        let trimmed = content.trim();
        if trimmed.is_empty() {
            continue;
        }
        if !combined.is_empty() {
            combined.push_str("\n\n");
        }
        combined.push_str(trimmed);
    }
    Ok(combined)
}

/// Build full prompt with sections in order:
/// 1. Role description (hardcoded instructions)
/// 2. MCP API docs
/// 3. Custom prompts (user context from prompt files)
/// 4. Task title
/// 5. Recent task history (latest chunk from get_history)
/// 6. Unchecked checklist items with ids
pub async fn build_full_prompt(
    user_context: &str,
    role: Role,
    task_id: u64,
    dispatcher: &ZbobrDispatcher,
) -> anyhow::Result<String> {
    let task = dispatcher.tasks().get_task(task_id).await?.snapshot().await?;
    let history = dispatcher.get_history(task_id, None).await?;
    let history_json = serde_json::to_string_pretty(&history.comments).unwrap_or_default();
    Ok(assemble_prompt(user_context, role, &task, &history_json))
}

/// Pure synchronous prompt assembly (used by tests and `build_full_prompt`).
fn assemble_prompt(
    user_context: &str,
    role: Role,
    task: &Task,
    history_json: &str,
) -> String {
    let task_title = &task.title;
    let hardcoded = match role {
        Role::Preparator => crate::preparator_instructions(),
        Role::Planner => crate::planner_instructions(),
        Role::Worker => crate::worker_instructions(),
        Role::Reviewer => crate::reviewer_instructions(),
        Role::Tester => crate::tester_instructions(),
        Role::Merger => crate::merger_instructions(),
    };

    let api_docs = match role {
        Role::Preparator => crate::PreparatorMcp::generate_api_docs(),
        Role::Planner => crate::PlannerMcp::generate_api_docs(),
        Role::Worker => crate::WorkerMcp::generate_api_docs(),
        Role::Reviewer => crate::ReviewerMcp::generate_api_docs(),
        Role::Tester => crate::TesterMcp::generate_api_docs(),
        Role::Merger => crate::MergerMcp::generate_api_docs(),
    };

    let mut sections = vec![hardcoded];

    // MCP API docs
    sections.push(api_docs);

    // Custom prompts from prompt files
    if !user_context.is_empty() {
        sections.push(user_context.to_owned());
    }

    // Task title
    if !task_title.is_empty() {
        sections.push(format!("# Current task: {task_title}"));
    }

    // Recent task history
    if !history_json.is_empty() {
        sections.push(format!("# Recent task history\n\n{history_json}"));
    }

    // Unchecked checklist items with ids
    let unchecked: Vec<_> = task
        .checklist
        .iter()
        .filter(|item| !item.checked)
        .collect();
    if !unchecked.is_empty() {
        let mut checklist_text = String::from("# Unchecked checklist items\n");
        for item in &unchecked {
            checklist_text.push_str(&format!("\n- [ ] [id: {}] {}", item.id, item.text));
        }
        sections.push(checklist_text);
    }

    sections.join("\n\n---\n\n")
}

/// Validate that all specified prompt files exist.
/// Returns an error listing all missing files if any are not found.
pub fn validate_prompts(prompts: &Prompts) -> anyhow::Result<()> {
    let mut missing_files = Vec::new();

    for path in &prompts.preparator {
        if !file_exists(path, prompts.base_path.as_ref()) {
            missing_files.push(path.clone());
        }
    }
    for path in &prompts.planner {
        if !file_exists(path, prompts.base_path.as_ref()) {
            missing_files.push(path.clone());
        }
    }
    for path in &prompts.worker {
        if !file_exists(path, prompts.base_path.as_ref()) {
            missing_files.push(path.clone());
        }
    }
    for path in &prompts.reviewer {
        if !file_exists(path, prompts.base_path.as_ref()) {
            missing_files.push(path.clone());
        }
    }
    for path in &prompts.tester {
        if !file_exists(path, prompts.base_path.as_ref()) {
            missing_files.push(path.clone());
        }
    }
    for path in &prompts.merger {
        if !file_exists(path, prompts.base_path.as_ref()) {
            missing_files.push(path.clone());
        }
    }

    if !missing_files.is_empty() {
        let missing_list = missing_files
            .iter()
            .map(|p| format!("  - {}", p.display()))
            .collect::<Vec<_>>()
            .join("\n");
        return Err(anyhow::anyhow!(
            "The following prompt files do not exist:\n{}",
            missing_list
        ));
    }

    Ok(())
}

/// Check if a file exists, resolving relative paths with base_path if provided.
fn file_exists(path: &PathBuf, base_path: Option<&PathBuf>) -> bool {
    let resolved_path = if let Some(base) = base_path {
        if path.is_relative() {
            base.join(path)
        } else {
            path.clone()
        }
    } else if path.is_relative() {
        match std::env::current_dir() {
            Ok(cwd) => cwd.join(path),
            Err(_) => return false,
        }
    } else {
        path.clone()
    };

    resolved_path.exists()
}

impl Prompts {
    /// Build the full prompt for the given role.
    pub async fn build_prompt(
        &self,
        role: Role,
        task_id: u64,
        dispatcher: &ZbobrDispatcher,
    ) -> anyhow::Result<String> {
        let base_prompt = match role {
            Role::Preparator => load_prompts(&self.preparator, self.base_path.as_ref())?,
            Role::Planner => load_prompts(&self.planner, self.base_path.as_ref())?,
            Role::Worker => load_prompts(&self.worker, self.base_path.as_ref())?,
            Role::Reviewer => load_prompts(&self.reviewer, self.base_path.as_ref())?,
            Role::Tester => load_prompts(&self.tester, self.base_path.as_ref())?,
            Role::Merger => load_prompts(&self.merger, self.base_path.as_ref())?,
        };
        build_full_prompt(&base_prompt, role, task_id, dispatcher).await
    }
}

#[cfg(test)]
mod tests {
    use std::{fs, io::Write};

    use tempfile::TempDir;

    use zbobr_api::Stage;

    use super::*;

    fn dummy_task(title: &str) -> Task {
        Task {
            id: 1,
            title: title.to_owned(),
            description: String::new(),
            stage: Stage::Pending,
            destination_repository: None,
            destination_branch: None,
            work_branch: None,
            parameters: Default::default(),
            checklist: vec![],
            signal: None,
            conflict: false,
            pause: false,
            confirm: false,
            etag: None,
        }
    }

    fn write_file(dir: &TempDir, name: &str, content: &str) -> PathBuf {
        let path = dir.path().join(name);
        let mut f = fs::File::create(&path).unwrap();
        f.write_all(content.as_bytes()).unwrap();
        path
    }

    fn default_config() -> ZbobrDispatcherConfig {
        let mut cfg = ZbobrDispatcherConfig::default();
        cfg.preparator.prompts = vec![];
        cfg.planner.prompts = vec![];
        cfg.worker.prompts = vec![];
        cfg.reviewer.prompts = vec![];
        cfg.merger.prompts = vec![];
        cfg.prompts_path = None;
        cfg
    }

    // --- load_prompts ---

    #[test]
    fn load_prompts_reads_existing_file() {
        let dir = TempDir::new().unwrap();
        let path = write_file(&dir, "p.md", "  hello world  ");
        let result = load_prompts(&[path], None).unwrap();
        assert_eq!(result, "hello world");
    }

    #[test]
    fn load_prompts_errors_on_missing_file() {
        let result = load_prompts(&[PathBuf::from("/nonexistent/path/prompt.md")], None);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("Failed to read prompt file"));
    }

    #[test]
    fn load_prompts_concatenates_multiple_files() {
        let dir = TempDir::new().unwrap();
        let a = write_file(&dir, "a.md", "first");
        let b = write_file(&dir, "b.md", "second");
        let result = load_prompts(&[a, b], None).unwrap();
        assert_eq!(result, "first\n\nsecond");
    }

    #[test]
    fn load_prompts_skips_empty_files() {
        let dir = TempDir::new().unwrap();
        let empty = write_file(&dir, "empty.md", "   \n  \n");
        let real = write_file(&dir, "real.md", "content");
        let result = load_prompts(&[empty, real], None).unwrap();
        assert_eq!(result, "content");
    }

    #[test]
    fn load_prompts_resolves_relative_path_with_base_path() {
        let dir = TempDir::new().unwrap();
        write_file(&dir, "custom.md", "custom content");
        let relative = PathBuf::from("custom.md");
        let base = dir.path().to_path_buf();
        let result = load_prompts(&[relative], Some(&base)).unwrap();
        assert_eq!(result, "custom content");
    }

    #[test]
    fn load_prompts_absolute_path_ignores_base_path() {
        let dir = TempDir::new().unwrap();
        let abs = write_file(&dir, "abs.md", "absolute content");
        let fake_base = PathBuf::from("/nonexistent/base");
        let result = load_prompts(&[abs], Some(&fake_base)).unwrap();
        assert_eq!(result, "absolute content");
    }

    // --- resolve_prompts ---

    #[test]
    fn resolve_prompts_uses_config_when_args_empty() {
        let config = default_config();
        let args = ZbobrDispatcherArgs::default();
        let prompts = resolve_prompts(&args, &config);
        assert_eq!(prompts.preparator, config.preparator.prompts);
        assert_eq!(prompts.planner, config.planner.prompts);
        assert_eq!(prompts.worker, config.worker.prompts);
        assert_eq!(prompts.reviewer, config.reviewer.prompts);
        assert_eq!(prompts.merger, config.merger.prompts);
        assert_eq!(prompts.base_path, None);
    }

    #[test]
    fn resolve_prompts_args_override_config() {
        let config = default_config();
        let mut args = ZbobrDispatcherArgs::default();
        args.preparator.prompts = Some(vec![PathBuf::from("override.md")]);
        args.planner.prompts = Some(vec![PathBuf::from("plan_override.md")]);
        let prompts = resolve_prompts(&args, &config);
        assert_eq!(prompts.preparator, vec![PathBuf::from("override.md")]);
        assert_eq!(prompts.planner, vec![PathBuf::from("plan_override.md")]);
        // Other roles still use config
        assert_eq!(prompts.worker, config.worker.prompts);
    }

    #[test]
    fn resolve_prompts_merger_args_override_config() {
        let config = default_config();
        let mut args = ZbobrDispatcherArgs::default();
        args.merger.prompts = Some(vec![PathBuf::from("merger_override.md")]);
        let prompts = resolve_prompts(&args, &config);
        assert_eq!(prompts.merger, vec![PathBuf::from("merger_override.md")]);
    }

    #[test]
    fn resolve_prompts_base_path_from_args_overrides_config() {
        let mut config = default_config();
        config.prompts_path = Some(PathBuf::from("/config/prompts"));
        let args = ZbobrDispatcherArgs {
            prompts_path: Some(PathBuf::from("/args/prompts")),
            ..Default::default()
        };
        let prompts = resolve_prompts(&args, &config);
        assert_eq!(prompts.base_path, Some(PathBuf::from("/args/prompts")));
    }

    #[test]
    fn resolve_prompts_base_path_falls_back_to_config() {
        let mut config = default_config();
        config.prompts_path = Some(PathBuf::from("/config/prompts"));
        let args = ZbobrDispatcherArgs::default();
        let prompts = resolve_prompts(&args, &config);
        assert_eq!(prompts.base_path, Some(PathBuf::from("/config/prompts")));
    }

    #[test]
    fn resolve_prompts_uses_stage_config_if_present() {
        let mut config = default_config();
        config.preparator.prompts = vec![PathBuf::from("stage.md")];
        let args = ZbobrDispatcherArgs::default();
        let prompts = resolve_prompts(&args, &config);
        assert_eq!(prompts.preparator, vec![PathBuf::from("stage.md")]);
    }

    // --- assemble_prompt ---

    #[test]
    fn assemble_prompt_includes_user_context() {
        let prompt = assemble_prompt("my custom instructions", Role::Worker, &dummy_task(""), "");
        assert!(prompt.contains("my custom instructions"));
    }

    #[test]
    fn assemble_prompt_empty_context_omits_user_section() {
        let prompt_empty = assemble_prompt("", Role::Worker, &dummy_task(""), "");
        let prompt_with = assemble_prompt("UNIQUE_MARKER", Role::Worker, &dummy_task(""), "");
        assert!(!prompt_empty.contains("UNIQUE_MARKER"));
        // With context is longer (has the extra context section)
        assert!(prompt_with.len() > prompt_empty.len());
    }

    // --- load_prompts + assemble_prompt integration ---

    #[test]
    fn load_prompts_content_appears_in_assembled_prompt() {
        let dir = TempDir::new().unwrap();
        let path = write_file(&dir, "worker.md", "do the work carefully");
        let loaded = load_prompts(&[path], None).unwrap();
        let result = assemble_prompt(&loaded, Role::Worker, &dummy_task(""), "");
        assert!(result.contains("do the work carefully"));
    }

    #[test]
    fn no_prompt_files_gives_empty_context() {
        let loaded = load_prompts(&[] as &[PathBuf], None).unwrap();
        let result = assemble_prompt(&loaded, Role::Worker, &dummy_task(""), "");
        let expected = assemble_prompt("", Role::Worker, &dummy_task(""), "");
        assert_eq!(result, expected);
    }

    #[test]
    fn load_prompts_with_base_path_resolves_relative_files() {
        let dir = TempDir::new().unwrap();
        write_file(&dir, "reviewer.md", "review carefully");
        let loaded = load_prompts(
            &[PathBuf::from("reviewer.md")],
            Some(&dir.path().to_path_buf()),
        )
        .unwrap();
        let result = assemble_prompt(&loaded, Role::Reviewer, &dummy_task(""), "");
        assert!(result.contains("review carefully"));
    }

    // --- validate_prompts ---

    #[test]
    fn validate_prompts_succeeds_with_existing_files() {
        let dir = TempDir::new().unwrap();
        let worker_file = write_file(&dir, "worker.md", "content");
        let prompts = Prompts {
            base_path: None,
            preparator: vec![],
            planner: vec![],
            worker: vec![worker_file],
            reviewer: vec![],
            tester: vec![],
            merger: vec![],
        };
        assert!(validate_prompts(&prompts).is_ok());
    }

    #[test]
    fn validate_prompts_succeeds_with_empty_prompts() {
        let prompts = Prompts {
            base_path: None,
            preparator: vec![],
            planner: vec![],
            worker: vec![],
            reviewer: vec![],
            tester: vec![],
            merger: vec![],
        };
        assert!(validate_prompts(&prompts).is_ok());
    }

    #[test]
    fn validate_prompts_fails_with_missing_file() {
        let prompts = Prompts {
            base_path: None,
            preparator: vec![],
            planner: vec![],
            worker: vec![PathBuf::from("/nonexistent/worker.md")],
            reviewer: vec![],
            tester: vec![],
            merger: vec![],
        };
        let result = validate_prompts(&prompts);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("do not exist"));
        assert!(err.contains("/nonexistent/worker.md"));
    }

    #[test]
    fn validate_prompts_lists_all_missing_files() {
        let prompts = Prompts {
            base_path: None,
            preparator: vec![PathBuf::from("/missing1.md")],
            planner: vec![PathBuf::from("/missing2.md")],
            worker: vec![],
            reviewer: vec![],
            tester: vec![],
            merger: vec![],
        };
        let result = validate_prompts(&prompts);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("/missing1.md"));
        assert!(err.contains("/missing2.md"));
    }

    #[test]
    fn validate_prompts_resolves_relative_paths_with_base_path() {
        let dir = TempDir::new().unwrap();
        write_file(&dir, "worker.md", "content");
        let prompts = Prompts {
            base_path: Some(dir.path().to_path_buf()),
            preparator: vec![],
            planner: vec![],
            worker: vec![PathBuf::from("worker.md")],
            reviewer: vec![],
            tester: vec![],
            merger: vec![],
        };
        assert!(validate_prompts(&prompts).is_ok());
    }

    #[test]
    fn validate_prompts_detects_missing_relative_paths_with_base_path() {
        let dir = TempDir::new().unwrap();
        let prompts = Prompts {
            base_path: Some(dir.path().to_path_buf()),
            preparator: vec![],
            planner: vec![],
            worker: vec![PathBuf::from("missing.md")],
            reviewer: vec![],
            tester: vec![],
            merger: vec![],
        };
        let result = validate_prompts(&prompts);
        assert!(result.is_err());
    }
}
