use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};

pub mod macros;
pub use macros::config_struct;

/// Trait implemented by every config `*Args` struct generated by the [`config_struct`] macro.
///
/// It is the counterpart to clap's [`Args`] trait but carries an explicit `prefix` so that the
/// same struct can be registered in a clap [`Command`] with different argument names depending on
/// where it is nested.  The generated [`clap::Args`] / [`clap::FromArgMatches`] impls delegate to
/// these methods with an empty prefix.
pub trait PrefixedArgs: Sized {
    /// Add all arguments for this struct to `cmd`, prepending `prefix` to every
    /// argument id (and converting `.` → `-` for the `--long` form).
    fn augment_args_prefixed(cmd: clap::Command, prefix: &str) -> clap::Command;

    /// Read back the struct from already-parsed `ArgMatches`, using the same
    /// `prefix` that was passed to [`augment_args_prefixed`].
    fn from_matches_prefixed(m: &clap::ArgMatches, prefix: &str) -> clap::error::Result<Self>;
}

/// Resolve a relative path against a base directory; absolute paths are returned as-is.
pub fn resolve_path(path: PathBuf, base: &Path) -> PathBuf {
    if path.is_relative() {
        base.join(path)
    } else {
        path
    }
}

// Replace characters that are unsafe or invalid in filenames with '_'.
// Allows ASCII alphanumerics, '-', '_', and '.'.
fn sanitize_filename(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Configure git user settings for a repository.
/// Sets user.name and user.email at the repository level.
pub async fn configure_git_user(
    work_dir: &Path,
    git_user_name: &str,
    git_user_email: &str,
) -> Result<()> {
    let config_user_status = tokio::process::Command::new("git")
        .args(["config", "--local", "user.name", git_user_name])
        .current_dir(work_dir)
        .status()
        .await
        .context("Failed to set git user.name")?;

    if !config_user_status.success() {
        anyhow::bail!("git config user.name failed");
    }

    let config_email_status = tokio::process::Command::new("git")
        .args(["config", "--local", "user.email", git_user_email])
        .current_dir(work_dir)
        .status()
        .await
        .context("Failed to set git user.email")?;

    if !config_email_status.success() {
        anyhow::bail!("git config user.email failed");
    }

    tracing::info!(
        "Configured git user '{}' <{}> in {}",
        git_user_name,
        git_user_email,
        work_dir.display()
    );

    Ok(())
}

/// Create a placeholder file in a branch to ensure it has at least one commit.
///
/// Behavior mirrors the old implementation in `zbobr-dispatcher`:
/// - Creates `.zbobr/{sanitized_branch}` file
/// - Stages it with `git add` and commits it with `git commit`
///
/// Errors include helpful context for diagnostics.
pub async fn create_placeholder_commit(work_dir: &Path, branch_name: &str) -> Result<()> {
    let zbobr_dir = work_dir.join(".zbobr");
    let sanitized_branch = sanitize_filename(branch_name);
    let placeholder_path = zbobr_dir.join(&sanitized_branch);

    // Create .zbobr directory
    tokio::fs::create_dir_all(&zbobr_dir)
        .await
        .map_err(|e| anyhow!("Failed to create .zbobr directory: {}", e))?;

    // Create placeholder file with extended diagnostics on failure
    match tokio::fs::File::create(&placeholder_path).await {
        Ok(_) => {}
        Err(e) => {
            let kind = e.kind();
            let raw = e.raw_os_error();

            let zbobr_exists = tokio::fs::metadata(&zbobr_dir).await.is_ok();
            let work_dir_meta = tokio::fs::metadata(work_dir).await;
            let work_dir_readonly = work_dir_meta
                .as_ref()
                .map(|m| m.permissions().readonly())
                .unwrap_or(false);

            anyhow::bail!(
                "Failed to create placeholder file: {} — attempted path: {} — work_dir: {} — .zbobr exists: {} — work_dir_readonly: {} — kind: {:?} — raw_os_error: {:?}",
                e,
                placeholder_path.display(),
                work_dir.display(),
                zbobr_exists,
                work_dir_readonly,
                kind,
                raw
            );
        }
    }

    // Stage the file
    let add_status = tokio::process::Command::new("git")
        .args(["add", &format!(".zbobr/{}", sanitized_branch)])
        .current_dir(work_dir)
        .status()
        .await
        .map_err(|e| anyhow!("Failed to run git add: {}", e))?;

    if !add_status.success() {
        anyhow::bail!("git add for placeholder failed (exit != 0)");
    }

    // Commit the file
    let commit_msg = format!("chore: add branch placeholder {}", branch_name);
    let commit_status = tokio::process::Command::new("git")
        .args(["commit", "-m", &commit_msg])
        .current_dir(work_dir)
        .status()
        .await
        .map_err(|e| anyhow!("Failed to run git commit: {}", e))?;

    if !commit_status.success() {
        anyhow::bail!("git commit for placeholder failed (exit != 0)");
    }

    Ok(())
}

/// Delete the placeholder file created by [`create_placeholder_commit`] and commit the removal.
///
/// If the placeholder file does not exist this function is a no-op (returns `Ok(())`).
pub async fn delete_placeholder_commit(work_dir: &Path, branch_name: &str) -> Result<()> {
    let sanitized_branch = sanitize_filename(branch_name);
    let placeholder_path = work_dir.join(".zbobr").join(&sanitized_branch);

    if !tokio::fs::try_exists(&placeholder_path).await.unwrap_or(false) {
        tracing::debug!(
            "Placeholder file {} does not exist — skipping deletion",
            placeholder_path.display()
        );
        return Ok(());
    }

    let rm_status = tokio::process::Command::new("git")
        .args(["rm", "-f", &format!(".zbobr/{}", sanitized_branch)])
        .current_dir(work_dir)
        .status()
        .await
        .map_err(|e| anyhow!("Failed to run git rm for placeholder: {}", e))?;

    if !rm_status.success() {
        anyhow::bail!("git rm for placeholder failed (exit != 0)");
    }

    let commit_msg = format!("chore: remove branch placeholder {}", branch_name);
    let commit_status = tokio::process::Command::new("git")
        .args(["commit", "-m", &commit_msg])
        .current_dir(work_dir)
        .status()
        .await
        .map_err(|e| anyhow!("Failed to run git commit for placeholder removal: {}", e))?;

    if !commit_status.success() {
        anyhow::bail!("git commit for placeholder removal failed (exit != 0)");
    }

    tracing::info!(
        "Deleted branch placeholder .zbobr/{} and committed",
        sanitized_branch
    );

    Ok(())
}
