use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

pub mod macros;
pub use macros::config_struct;

/// Trait implemented by every config `*Args` struct generated by the [`config_struct`] macro.
///
/// It is the counterpart to clap's [`Args`] trait but carries an explicit `prefix` so that the
/// same struct can be registered in a clap [`Command`] with different argument names depending on
/// where it is nested.  The generated [`clap::Args`] / [`clap::FromArgMatches`] impls delegate to
/// these methods with an empty prefix.
pub trait PrefixedArgs: Sized {
    /// Add all arguments for this struct to `cmd`, prepending `prefix` to every
    /// argument id (and converting `.` → `-` for the `--long` form).
    fn augment_args_prefixed(cmd: clap::Command, prefix: &str) -> clap::Command;

    /// Read back the struct from already-parsed `ArgMatches`, using the same
    /// `prefix` that was passed to [`augment_args_prefixed`].
    fn from_matches_prefixed(m: &clap::ArgMatches, prefix: &str) -> clap::error::Result<Self>;
}

/// Resolve a relative path against a base directory; absolute paths are returned as-is.
pub fn resolve_path(path: PathBuf, base: &Path) -> PathBuf {
    if path.is_relative() {
        base.join(path)
    } else {
        path
    }
}

/// Run a git command in `dir`, returning an error with context on failure.
pub async fn git(dir: &Path, args: &[&str]) -> Result<()> {
    let status = tokio::process::Command::new("git")
        .args(args)
        .current_dir(dir)
        .status()
        .await
        .with_context(|| format!("Failed to spawn: git {}", args.join(" ")))?;
    if !status.success() {
        anyhow::bail!("git {} failed in {}", args.join(" "), dir.display());
    }
    Ok(())
}

/// Run a git command in `dir` and capture stdout (trimmed).
pub async fn git_output(dir: &Path, args: &[&str]) -> Result<String> {
    let output = tokio::process::Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .await
        .with_context(|| format!("Failed to spawn: git {}", args.join(" ")))?;
    if !output.status.success() {
        anyhow::bail!("git {} failed in {}", args.join(" "), dir.display());
    }
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

/// Run a git command in `dir`, returning `Ok(true)` if exit code 0, `Ok(false)` otherwise.
/// Stderr is suppressed so that expected failures (e.g. checking if a ref exists) don't
/// produce noisy output.
pub async fn git_check(dir: &Path, args: &[&str]) -> Result<bool> {
    let status = tokio::process::Command::new("git")
        .args(args)
        .current_dir(dir)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .await
        .with_context(|| format!("Failed to spawn: git {}", args.join(" ")))?;
    Ok(status.success())
}

/// Configure git user settings for a repository.
/// Sets user.name and user.email at the repository level.
pub async fn configure_git_user(
    work_dir: &Path,
    git_user_name: &str,
    git_user_email: &str,
) -> Result<()> {
    git(work_dir, &["config", "--local", "user.name", git_user_name]).await?;
    git(
        work_dir,
        &["config", "--local", "user.email", git_user_email],
    )
    .await?;

    tracing::info!(
        "Configured git user '{}' <{}> in {}",
        git_user_name,
        git_user_email,
        work_dir.display()
    );

    Ok(())
}

/// Create an empty placeholder commit in a branch to ensure it has at least one commit
/// ahead of the base branch.
///
/// Uses `git commit --allow-empty` so no files are created or staged.
pub async fn create_placeholder_commit(work_dir: &Path, branch_name: &str) -> Result<()> {
    let commit_msg = format!("chore: add branch placeholder {}", branch_name);
    git(work_dir, &["commit", "--allow-empty", "-m", &commit_msg]).await?;
    Ok(())
}

/// Clean up stale git worktree state for a branch before creating a new worktree.
///
/// `workspace_path` is the intended destination for the new worktree.
///
/// 1. Prunes worktree references whose directories no longer exist.
/// 2. Scans remaining worktrees for `work_branch`:
///    - **Functional at `workspace_path`** (`.git` entry exists and `git
///      status` succeeds) — already set up correctly, nothing to do.
///    - **Functional at a different path** — someone else is using it, returns
///      an error.
///    - **Non-functional** (directory empty/missing, no `.git`, or `git status`
///      fails) — stale reference, force-removed regardless of path.
pub async fn cleanup_worktree_for_branch(
    bare_dir: &Path,
    work_branch: &str,
    workspace_path: &Path,
) -> Result<()> {
    git(bare_dir, &["worktree", "prune"]).await?;

    let worktree_list = git_output(bare_dir, &["worktree", "list", "--porcelain"]).await?;
    let mut current_wt_path: Option<String> = None;
    #[allow(clippy::collapsible_if)]
    for line in worktree_list.lines() {
        if let Some(p) = line.strip_prefix("worktree ") {
            current_wt_path = Some(p.to_string());
        } else if let Some(b) = line.strip_prefix("branch refs/heads/") {
            if b == work_branch {
                if let Some(ref wt) = current_wt_path {
                    let wt_path = Path::new(wt);
                    // A worktree is functional if its directory has a .git
                    // entry AND `git status` succeeds in it.
                    let functional = wt_path.join(".git").exists()
                        && git_check(wt_path, &["status"]).await.unwrap_or(false);

                    if functional {
                        // Compare canonicalized paths to avoid ./foo vs foo mismatches
                        let wt_canon = wt_path.canonicalize().ok();
                        let ws_canon = workspace_path.canonicalize().ok();
                        if wt_canon.is_some() && wt_canon == ws_canon {
                            // Already set up at the right place, nothing to do
                            return Ok(());
                        }
                        anyhow::bail!(
                            "Branch '{}' is already checked out in worktree '{}', \
                             cannot create another at '{}'",
                            work_branch,
                            wt,
                            workspace_path.display()
                        );
                    }

                    tracing::warn!(
                        "Branch '{}' has stale worktree reference '{}', removing it",
                        work_branch,
                        wt
                    );
                    let _ = git(bare_dir, &["worktree", "remove", "--force", wt]).await;
                }
            }
        }
    }

    Ok(())
}

/// Rewrite commit authors on a worktree branch using `git filter-branch`.
///
/// Rewrites all commits between `dest_branch` and `HEAD` to use the given
/// `git_user_name` and `git_user_email` as both author and committer.
/// Unlike rebase, filter-branch does not replay changes, so it cannot
/// produce merge conflicts.
pub async fn rewrite_authors_on_worktree(
    work_dir: &Path,
    dest_branch: &str,
    git_user_name: &str,
    git_user_email: &str,
) -> Result<()> {
    // Get absolute path to the git repository
    let git_root = git_output(work_dir, &["rev-parse", "--show-toplevel"]).await?;
    let git_root_path = PathBuf::from(&git_root);

    // Configure git user locally
    configure_git_user(&git_root_path, git_user_name, git_user_email).await?;

    // Use git filter-branch to rewrite author/committer in-place.
    let filter_cmd = format!(
        "git filter-branch -f --env-filter '\
            export GIT_AUTHOR_NAME=\"{name}\";\
            export GIT_AUTHOR_EMAIL=\"{email}\";\
            export GIT_COMMITTER_NAME=\"{name}\";\
            export GIT_COMMITTER_EMAIL=\"{email}\";\
        ' '{dest}'..HEAD",
        name = git_user_name,
        email = git_user_email,
        dest = dest_branch,
    );
    let filter_output = tokio::process::Command::new("sh")
        .arg("-c")
        .arg(&filter_cmd)
        .current_dir(&git_root_path)
        .output()
        .await;
    match filter_output {
        Ok(output) if output.status.success() => {
            tracing::info!("Successfully rewrote commit authors");
            Ok(())
        }
        Ok(output) => Err(anyhow::anyhow!(
            "Failed to rewrite commit authors: {}",
            String::from_utf8_lossy(&output.stderr)
        )),
        Err(e) => Err(anyhow::anyhow!(
            "Error running git filter-branch for author rewriting: {}",
            e
        )),
    }
}

/// No-op: placeholder commits are now empty commits that don't need cleanup.
///
/// Kept for backward compatibility with callers.
pub async fn delete_placeholder_commit(_work_dir: &Path, _branch_name: &str) -> Result<()> {
    Ok(())
}
