[package]
name = "zbobr-dispatcher"
version = "0.1.0"
edition = "2024"

[dependencies]
zbobr-api = { version = "0.1.0", path = "../zbobr-api" }
zbobr-utility = { version = "0.1.0", path = "../zbobr-utility" }
zbobr-task-backend-github = { version = "0.1.0", path = "../zbobr-task-backend-github" }
zbobr-task-backend-fs = { version = "0.1.0", path = "../zbobr-task-backend-fs" }
zbobr-repo-backend-github = { version = "0.1.0", path = "../zbobr-repo-backend-github" }
zbobr-repo-backend-fs = { version = "0.1.0", path = "../zbobr-repo-backend-fs" }
zbobr-executor-claude = { version = "0.1.0", path = "../zbobr-executor-claude" }
zbobr-executor-copilot = { version = "0.1.0", path = "../zbobr-executor-copilot" }
zbobr-executor-mcp-tester = { version = "0.1.0", path = "../zbobr-executor-mcp-tester" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
rmcp = { workspace = true }
axum = { workspace = true }
schemars = { workspace = true }
anyhow = { workspace = true }
hostname = { workspace = true }
clap = { workspace = true, features = ["derive"] }
paste.workspace = true
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
anyhow = { workspace = true }
rustls = { workspace = true }
serial_test = "3"
