[package]
name = "zbobr-dispatcher"
version = "0.1.0"
edition = "2024"

[dependencies]
zbobr-utility = { version = "0.1.0", path = "../zbobr-utility" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
rmcp = { workspace = true }
axum = { workspace = true }
schemars = { workspace = true }
anyhow = { workspace = true }
hostname = { workspace = true }
clap = { workspace = true, features = ["derive"] }
paste.workspace = true

[dev-dependencies]
toml = { workspace = true }
tempfile = { workspace = true }
anyhow = { workspace = true }
rustls = { workspace = true }
