use std::{collections::HashMap, path::PathBuf};

use indexmap::IndexMap;
use zbobr_utility::MergeToml;
use zbobr_utility::config_struct;

use crate::{
    config_tools::McpTool,
    task::{Model, Pipeline, Stage, Tool},
};
use zbobr_utility::Secret;

/// Auto-generated by #[config_struct] for every config struct.
pub trait Config: Sized {
    type Toml: Default + for<'de> serde::Deserialize<'de>;
    type Args: clap::Args + zbobr_utility::PrefixedArgs + Default + Clone;
    fn build(toml: Option<Self::Toml>, args: Self::Args, config_dir: &std::path::Path) -> Self;
}

/// Definition of a role: which MCP tools it can access, an optional prompt file, and optional tool override.
///
/// `mcp = None` means the field was absent in the config (inherit from base during merging,
/// or no tools at runtime). `mcp = Some(vec![])` explicitly allows no tools.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Default)]
#[serde(deny_unknown_fields)]
pub struct RoleDefinition {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp: Option<Vec<McpTool>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<PathBuf>,
    /// Tool name override for this role. Overrides the global dispatcher `tool`.
    /// Stage-level `tool` takes precedence over this.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
}

impl RoleDefinition {
    /// Resolve relative path fields against the given base directory.
    pub fn resolve_paths(self, config_dir: &std::path::Path) -> Self {
        Self {
            prompt: self
                .prompt
                .map(|p| zbobr_utility::resolve_path(p, config_dir)),
            ..self
        }
    }
}

impl zbobr_utility::MergeToml for RoleDefinition {
    fn merge_toml(self, other: Self) -> Self {
        Self {
            mcp: other.mcp.or(self.mcp),
            prompt: other.prompt.or(self.prompt),
            tool: other.tool.or(self.tool),
        }
    }
}

/// A provider definition: a named executor configuration with optional inheritance.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct ProviderDefinition {
    /// Executor type (e.g. "claude", "copilot", "mcp-tester").
    /// Required unless `parent` is set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor: Option<String>,
    /// Parent provider to inherit settings from. Child fields override parent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<Provider>,
    /// Selection priority. Higher values are preferred. Omit to inherit from
    /// parent (root providers default to 10).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// Enable plan mode for this provider. Overrides any executor default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_mode: Option<bool>,
    /// API key for the executor (e.g. Anthropic API key for the claude executor).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access_key: Option<Secret>,
}

impl zbobr_utility::MergeToml for ProviderDefinition {
    fn merge_toml(self, other: Self) -> Self {
        Self {
            executor: other.executor.or(self.executor),
            parent: other.parent.or(self.parent),
            priority: other.priority.or(self.priority),
            plan_mode: other.plan_mode.or(self.plan_mode),
            access_key: other.access_key.or(self.access_key),
        }
    }
}

/// A resolved provider with all inheritance fully flattened.
#[derive(Clone, Debug)]
pub struct ResolvedProvider {
    pub provider: Provider,
    pub executor: String,
    pub priority: i32,
    pub plan_mode: bool,
    pub access_key: Option<Secret>,
}

/// One entry within a named tool definition: a (provider, model) pair.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct ToolEntry {
    pub provider: Provider,
    pub model: Model,
    /// Per-entry priority override. When set, replaces the priority inherited from the provider.
    /// Use a lower value than the provider's default to mark this entry as a fallback.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
}

mod role;
pub use role::Role;
mod provider;
pub use provider::Provider;

/// A stage transition descriptor with an optional target stage and pause flag.
///
/// Accepts two TOML forms:
/// - String shorthand: `on_success = "stage_b"` → `{ next: Some("stage_b"), pause: false }`
/// - Full table: `on_success = { next = "stage_b", pause = true }`
///
/// Both `next` and `pause` are optional (defaults: `None` and `false`).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize)]
pub struct StageTransition {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<Stage>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub pause: bool,
}

impl StageTransition {
    pub fn stage(next: impl Into<Stage>) -> Self {
        Self {
            next: Some(next.into()),
            pause: false,
        }
    }

    pub fn pause() -> Self {
        Self {
            next: None,
            pause: true,
        }
    }
}

impl<'de> serde::Deserialize<'de> for StageTransition {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(serde::Deserialize)]
        #[serde(deny_unknown_fields)]
        struct FullTransition {
            #[serde(default)]
            next: Option<Stage>,
            #[serde(default)]
            pause: bool,
        }
        #[derive(serde::Deserialize)]
        #[serde(untagged)]
        enum Helper {
            Stage(Stage),
            Full(FullTransition),
        }
        match Helper::deserialize(deserializer)? {
            Helper::Stage(s) => Ok(StageTransition {
                next: Some(s),
                pause: false,
            }),
            Helper::Full(f) => Ok(StageTransition {
                next: f.next,
                pause: f.pause,
            }),
        }
    }
}

/// A single stage in the configurable pipeline.
///
/// The stage's name and pipeline are derived from its structural position
/// (key in the stages HashMap and key in the pipelines HashMap).
///
/// A stage must have exactly one of `role` (run an agent session) or
/// `call` (call another pipeline). They are mutually exclusive.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Default)]
#[serde(deny_unknown_fields)]
pub struct StageDefinition {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call: Option<Pipeline>,
    /// Tool name override for this stage. Overrides role-level and global `tool`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role_prompt: Option<PathBuf>,
    /// `None` means absent in config (inherit from base during merging, or no extra prompts at runtime).
    /// `Some(vec![])` explicitly sets an empty list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompts: Option<Vec<PathBuf>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_success: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_failure: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_intermediate: Option<StageTransition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_no_report: Option<StageTransition>,
}

impl StageDefinition {
    /// Resolve relative path fields against the given base directory.
    pub fn resolve_paths(self, config_dir: &std::path::Path) -> Self {
        Self {
            role_prompt: self
                .role_prompt
                .map(|p| zbobr_utility::resolve_path(p, config_dir)),
            prompts: self.prompts.map(|v| {
                v.into_iter()
                    .map(|p| zbobr_utility::resolve_path(p, config_dir))
                    .collect()
            }),
            ..self
        }
    }

    pub fn role_name(&self) -> Option<&str> {
        self.role.as_deref()
    }

    pub fn call_pipeline(&self) -> Option<&Pipeline> {
        self.call.as_ref()
    }

    pub fn is_call(&self) -> bool {
        self.call.is_some()
    }

    pub fn on_success(&self) -> Option<&StageTransition> {
        self.on_success.as_ref()
    }

    pub fn on_failure(&self) -> Option<&StageTransition> {
        self.on_failure.as_ref()
    }

    pub fn on_intermediate(&self) -> Option<&StageTransition> {
        self.on_intermediate.as_ref()
    }

    pub fn on_no_report(&self) -> Option<&StageTransition> {
        self.on_no_report.as_ref()
    }
}

impl zbobr_utility::MergeToml for StageDefinition {
    fn merge_toml(self, other: Self) -> Self {
        Self {
            role: other.role.or(self.role),
            call: other.call.or(self.call),
            tool: other.tool.or(self.tool),
            role_prompt: other.role_prompt.or(self.role_prompt),
            prompts: other.prompts.or(self.prompts),
            on_success: other.on_success.or(self.on_success),
            on_failure: other.on_failure.or(self.on_failure),
            on_intermediate: other.on_intermediate.or(self.on_intermediate),
            on_no_report: other.on_no_report.or(self.on_no_report),
        }
    }
}

/// Per-pipeline configuration: an ordered sequence of stages.
///
/// Stage order is determined by insertion order in the `IndexMap`.
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct PipelineConfig {
    #[serde(default)]
    pub stages: IndexMap<Stage, StageDefinition>,
}

impl PipelineConfig {
    /// Resolve relative path fields in all stages against the given base directory.
    pub fn resolve_paths(self, config_dir: &std::path::Path) -> Self {
        Self {
            stages: self
                .stages
                .into_iter()
                .map(|(name, stage)| (name, stage.resolve_paths(config_dir)))
                .collect(),
        }
    }

    /// Look up a stage by name.
    pub fn stage(&self, name: &str) -> Option<&StageDefinition> {
        self.stages.get(name)
    }

    /// Get the index of a stage in the order.
    pub fn stage_index(&self, name: &str) -> Option<usize> {
        self.stages.get_index_of(name)
    }

    /// Get the next stage after `name`.
    pub fn next_stage(&self, name: &str) -> Option<(&str, &StageDefinition)> {
        let idx = self.stages.get_index_of(name)?;
        let (next_name, def) = self.stages.get_index(idx + 1)?;
        Some((next_name.as_str(), def))
    }

    /// Get the first stage of this pipeline.
    pub fn first_stage(&self) -> Option<(&str, &StageDefinition)> {
        let (name, def) = self.stages.first()?;
        Some((name.as_str(), def))
    }

    /// Get the start stage for this pipeline (delegates to first_stage).
    pub fn start_stage(&self) -> Option<(&str, &StageDefinition)> {
        self.first_stage()
    }

    /// Validate pipeline configuration.
    pub fn validate(&self, pipeline_name: &str) -> anyhow::Result<()> {
        if self.stages.is_empty() {
            anyhow::bail!("Pipeline '{}' has no stages", pipeline_name);
        }
        for (sname, stage) in &self.stages {
            match (&stage.role, &stage.call) {
                (Some(_), Some(_)) => anyhow::bail!(
                    "Pipeline '{}' stage '{}' has both 'role' and 'call' — only one is allowed",
                    pipeline_name,
                    sname
                ),
                (None, None) => anyhow::bail!(
                    "Pipeline '{}' stage '{}' has neither 'role' nor 'call' — one is required",
                    pipeline_name,
                    sname
                ),
                _ => {}
            }
            if let Some(ref target) = stage.on_success.as_ref().and_then(|t| t.next.as_ref())
                && !self.stages.contains_key(target.as_str())
            {
                anyhow::bail!(
                    "Pipeline '{}' stage '{}' on_success references unknown stage '{}'",
                    pipeline_name,
                    sname,
                    target
                );
            }
            if let Some(ref target) = stage.on_failure.as_ref().and_then(|t| t.next.as_ref())
                && !self.stages.contains_key(target.as_str())
            {
                anyhow::bail!(
                    "Pipeline '{}' stage '{}' on_failure references unknown stage '{}'",
                    pipeline_name,
                    sname,
                    target
                );
            }
            if let Some(ref target) = stage.on_intermediate.as_ref().and_then(|t| t.next.as_ref())
                && !self.stages.contains_key(target.as_str())
            {
                anyhow::bail!(
                    "Pipeline '{}' stage '{}' on_intermediate references unknown stage '{}'",
                    pipeline_name,
                    sname,
                    target
                );
            }
        }
        Ok(())
    }
}

impl zbobr_utility::MergeToml for PipelineConfig {
    fn merge_toml(self, other: Self) -> Self {
        let mut stages = self.stages;
        for (k, v) in other.stages {
            if let Some(base_v) = stages.get(&k).cloned() {
                stages.insert(k, base_v.merge_toml(v));
            } else {
                stages.insert(k, v);
            }
        }
        Self { stages }
    }
}

/// Top-level workflow configuration: a container of named pipelines and shared roles.
///
/// Defined manually (not via `#[config_struct]`) because it needs
/// custom `Config` impl with `WorkflowArgs` / `WorkflowToml`.
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowConfig {
    /// Base directory for prompt files; prepended to relative prompt paths.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompts_dir: Option<PathBuf>,
    #[serde(default)]
    pub roles: IndexMap<String, RoleDefinition>,
    #[serde(default)]
    pub pipelines: HashMap<Pipeline, PipelineConfig>,
}

/// TOML representation of WorkflowConfig (all fields optional).
#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize)]
#[serde(deny_unknown_fields)]
pub struct WorkflowToml {
    #[serde(default)]
    pub prompts_dir: Option<PathBuf>,
    #[serde(default)]
    pub roles: Option<IndexMap<String, RoleDefinition>>,
    #[serde(default)]
    pub pipelines: Option<HashMap<Pipeline, PipelineConfig>>,
}

/// CLI arguments for WorkflowConfig (empty — no CLI-overridable fields).
#[derive(Clone, Debug, Default)]
pub struct WorkflowArgs;

impl clap::Args for WorkflowArgs {
    fn augment_args(cmd: clap::Command) -> clap::Command {
        cmd
    }
    fn augment_args_for_update(cmd: clap::Command) -> clap::Command {
        cmd
    }
}

impl clap::FromArgMatches for WorkflowArgs {
    fn from_arg_matches(_matches: &clap::ArgMatches) -> Result<Self, clap::Error> {
        Ok(WorkflowArgs)
    }
    fn update_from_arg_matches(&mut self, _matches: &clap::ArgMatches) -> Result<(), clap::Error> {
        Ok(())
    }
}

impl zbobr_utility::PrefixedArgs for WorkflowArgs {
    fn augment_args_prefixed(cmd: clap::Command, _prefix: &str) -> clap::Command {
        cmd
    }
    fn from_matches_prefixed(
        _matches: &clap::ArgMatches,
        _prefix: &str,
    ) -> Result<Self, clap::Error> {
        Ok(WorkflowArgs)
    }
}

impl WorkflowArgs {
    pub fn has_overrides(&self) -> bool {
        false
    }
}

impl WorkflowToml {
    pub fn merge_with_args(self, _args: WorkflowArgs) -> Self {
        self
    }

    pub fn merge_toml(self, other: Self) -> Self {
        Self {
            prompts_dir: other.prompts_dir.or(self.prompts_dir),
            roles: match (self.roles, other.roles) {
                (Some(mut base), Some(over)) => {
                    for (k, v) in over {
                        if let Some(base_v) = base.get(&k).cloned() {
                            base.insert(k, base_v.merge_toml(v));
                        } else {
                            base.insert(k, v);
                        }
                    }
                    Some(base)
                }
                (None, over) => over,
                (base, None) => base,
            },
            pipelines: match (self.pipelines, other.pipelines) {
                (Some(mut base), Some(over)) => {
                    for (k, v) in over {
                        if let Some(base_v) = base.get(&k).cloned() {
                            base.insert(k, base_v.merge_toml(v));
                        } else {
                            base.insert(k, v);
                        }
                    }
                    Some(base)
                }
                (None, over) => over,
                (base, None) => base,
            },
        }
    }

    /// Resolve relative path fields against the given base directory.
    ///
    /// `prompts_dir` is resolved against `config_dir`.  Role and stage prompt
    /// paths are resolved against the *effective* prompt base: the resolved
    /// `prompts_dir` when present, otherwise `config_dir`.  This preserves the
    /// runtime contract in `prompt_files_for_stage`, which only prefixes
    /// *relative* paths with `prompts_dir`; by eagerly making paths absolute
    /// under the right base here, the dispatcher sees absolute paths and skips
    /// the prefix step correctly.
    pub fn resolve_paths(self, config_dir: &std::path::Path) -> Self {
        let resolved_prompts_dir = self
            .prompts_dir
            .map(|p| zbobr_utility::resolve_path(p, config_dir));
        let prompt_base: &std::path::Path = resolved_prompts_dir.as_deref().unwrap_or(config_dir);
        let roles = self.roles.map(|roles| {
            roles
                .into_iter()
                .map(|(name, role)| (name, role.resolve_paths(prompt_base)))
                .collect()
        });
        let pipelines = self.pipelines.map(|pipelines| {
            pipelines
                .into_iter()
                .map(|(name, pipeline)| (name, pipeline.resolve_paths(prompt_base)))
                .collect()
        });
        Self {
            prompts_dir: resolved_prompts_dir,
            roles,
            pipelines,
        }
    }

    pub fn try_into_config(self) -> anyhow::Result<WorkflowConfig> {
        Ok(WorkflowConfig {
            prompts_dir: self.prompts_dir,
            roles: self.roles.unwrap_or_default(),
            pipelines: self.pipelines.unwrap_or_default(),
        })
    }
}

impl Config for WorkflowConfig {
    type Toml = WorkflowToml;
    type Args = WorkflowArgs;

    fn build(toml: Option<Self::Toml>, _args: Self::Args, _config_dir: &std::path::Path) -> Self {
        match toml {
            Some(t) => WorkflowConfig {
                prompts_dir: t.prompts_dir,
                roles: t.roles.unwrap_or_default(),
                pipelines: t.pipelines.unwrap_or_default(),
            },
            None => WorkflowConfig::default(),
        }
    }
}

impl WorkflowConfig {
    /// Look up a pipeline by name.
    pub fn pipeline(&self, name: impl Into<Pipeline>) -> Option<&PipelineConfig> {
        self.pipelines.get(name.into().as_str())
    }

    /// Look up a stage in a specific pipeline.
    pub fn stage(&self, pipeline: impl Into<Pipeline>, stage: &str) -> Option<&StageDefinition> {
        self.pipelines.get(pipeline.into().as_str())?.stage(stage)
    }

    /// Get the start stage for a pipeline.
    pub fn start_stage_for_pipeline(
        &self,
        pipeline: impl Into<Pipeline>,
    ) -> Option<(&str, &StageDefinition)> {
        self.pipelines.get(pipeline.into().as_str())?.start_stage()
    }

    /// The default pipeline name.
    pub fn default_pipeline(&self) -> Pipeline {
        Pipeline::Main
    }

    /// All pipeline names.
    pub fn pipeline_names(&self) -> Vec<&Pipeline> {
        let mut names: Vec<&Pipeline> = self.pipelines.keys().collect();
        names.sort();
        names
    }

    /// Find the first stage with a given role (across all pipelines, preferring default pipeline).
    pub fn find_stage_by_role(&self, role: &str) -> Option<(&Pipeline, &str, &StageDefinition)> {
        let default = self.default_pipeline();
        if let Some(pipeline) = self.pipelines.get(default.as_str())
            && let Some((name, stage)) = pipeline
                .stages
                .iter()
                .find(|(_, s)| s.role_name() == Some(role))
        {
            return self
                .pipelines
                .get_key_value(default.as_str())
                .map(|(p, _)| (p, name.as_str(), stage));
        }
        for (pname, pipeline) in &self.pipelines {
            if let Some((sname, stage)) = pipeline
                .stages
                .iter()
                .find(|(_, s)| s.role_name() == Some(role))
            {
                return Some((pname, sname.as_str(), stage));
            }
        }
        None
    }

    /// Look up a role definition by name.
    pub fn role_definition(&self, role: &str) -> Option<&RoleDefinition> {
        self.roles.get(role)
    }

    /// Iterate over all stages as `(pipeline_name, stage_name, &StageDefinition)` tuples.
    pub fn all_stages(&self) -> Vec<(&Pipeline, &str, &StageDefinition)> {
        let mut result = Vec::new();
        for (pname, pipeline) in &self.pipelines {
            for (sname, stage) in &pipeline.stages {
                result.push((pname, sname.as_str(), stage));
            }
        }
        result
    }

    /// Validate the entire workflow configuration.
    pub fn validate(&self) -> anyhow::Result<()> {
        // Required pipelines must exist
        for required in [Pipeline::Main, Pipeline::Merge] {
            if !self.pipelines.contains_key(required.as_str()) {
                anyhow::bail!(
                    "Required pipeline '{}' is missing from [workflow.pipelines]",
                    required
                );
            }
        }

        let pipeline_names = self.pipeline_names();

        // Each pipeline must have valid order/stages
        for pname in &pipeline_names {
            let pipeline = self.pipelines.get(pname.as_str()).unwrap();
            pipeline.validate(pname.as_str())?;
        }

        // Every role-stage's role must exist in the roles map (if roles are configured)
        if !self.roles.is_empty() {
            for (pname, pipeline) in &self.pipelines {
                for (sname, stage) in &pipeline.stages {
                    if let Some(role) = &stage.role
                        && !self.roles.contains_key(role.as_str())
                    {
                        anyhow::bail!(
                            "Stage '{}/{}' references unknown role '{}' (not in [workflow.roles])",
                            pname,
                            sname,
                            role
                        );
                    }
                }
            }
        }

        // Every call-stage's target pipeline must exist
        for (pname, pipeline) in &self.pipelines {
            for (sname, stage) in &pipeline.stages {
                if let Some(target) = &stage.call
                    && !self.pipelines.contains_key(target.as_str())
                {
                    anyhow::bail!(
                        "Stage '{}/{}' calls unknown pipeline '{}'",
                        pname,
                        sname,
                        target
                    );
                }
            }
        }

        Ok(())
    }
}

/// Configuration for the zbobr dispatcher.
#[derive(Clone)]
#[config_struct]
pub struct ZbobrDispatcherConfig {
    /// Name of this zbobr instance. Used to label tasks (zbobr:<instance>) so that
    /// multiple instances can run against the same repository without interfering.
    pub instance: String,
    /// Workspaces directory; each task gets a separate subdirectory.
    #[config(path)]
    pub workspaces: std::path::PathBuf,
    /// Base port for the MCP server; zbobr scans upward from this port to find
    /// an available one.
    #[arg(default_value = "3000")]
    pub base_port: u16,
    /// Read-only GitHub token passed as GH_TOKEN/GITHUB_TOKEN to agent processes.
    /// This is a security boundary: it limits what agents can do on GitHub — agents must
    /// not have write access so that erroneous or misbehaving agents cannot modify remote
    /// repositories. Use a fine-grained token with read-only scopes (or no scopes at all
    /// for fully offline/mcp-tester runs). Defaults to `{ value = "not-configured" }` when omitted.
    /// Use `{ value = "token" }` for an inline token or `{ env = "VAR" }` to read from an env var.
    #[config(skip_args)]
    pub agent_github_token: Secret,
    /// Named provider definitions. Providers map a name to an executor + settings.
    #[config(skip_args)]
    pub providers: IndexMap<Provider, ProviderDefinition>,
    /// Named tool definitions. Each tool is a list of (provider, model) pairs.
    #[config(skip_args)]
    pub tools: IndexMap<String, Vec<ToolEntry>>,
    /// Seconds a provider is excluded from selection after a failure.
    #[config(skip_args)]
    pub provider_exclusion_secs: u64,
    /// Consecutive failures required before excluding a provider.
    #[config(skip_args)]
    pub provider_exclusion_fail_count: u32,
    /// Prefix for work branches (default: "zbobr_fix").
    pub work_branch_prefix: String,
    /// Git user name for commits made by the tool.
    pub git_user_name: String,
    /// Git user email for commits made by the tool.
    pub git_user_email: String,
    /// Rewrite commit authors after each stage completes to match configured git user.
    pub overwrite_author: bool,
    /// Maximum number of stages a task is allowed to pass before being auto-paused.
    /// When a task's stage_count reaches this limit, the task is paused automatically.
    /// Set to 0 to disable the limit. Default: 20.
    #[arg(default_value = "20")]
    pub max_task_stage_count: u64,
    /// Timezone for timestamps (e.g. "+0300", "-0500", "+03:00").
    /// If not set, the operating system's local timezone is used.
    pub timezone: Option<crate::task::FixedOffsetTz>,
}

impl Default for ZbobrDispatcherConfig {
    fn default() -> Self {
        Self {
            instance: "default".to_string(),
            workspaces: std::path::PathBuf::from("./workspaces"),
            base_port: 3000,
            agent_github_token: Secret::value("not-configured"),
            providers: IndexMap::new(),
            tools: IndexMap::new(),
            provider_exclusion_secs: 300,
            provider_exclusion_fail_count: 1,
            work_branch_prefix: "zbobr_fix".to_string(),
            git_user_name: String::new(),
            git_user_email: String::new(),
            overwrite_author: false,
            max_task_stage_count: 20,
            timezone: None,
        }
    }
}

impl ZbobrDispatcherConfig {
    /// Load configuration from environment variables only (backward compat).
    pub fn from_env() -> anyhow::Result<Self> {
        let cwd = std::env::current_dir()
            .map_err(|e| anyhow::anyhow!("Cannot get current directory: {e}"))?;
        Ok(<Self as Config>::build(
            None,
            ZbobrDispatcherArgs::default(),
            &cwd,
        ))
    }

    /// Returns the configured timezone offset, or the system's local timezone if not set.
    pub fn fixed_offset(&self) -> chrono::FixedOffset {
        match &self.timezone {
            Some(tz) => **tz,
            None => *chrono::Local::now().offset(),
        }
    }

    /// Validate configuration consistency and resolve all secrets.
    pub fn validate(&mut self) -> anyhow::Result<()> {
        // Verify parent references are valid
        for (provider_name, provider) in &self.providers {
            if let Some(ref parent) = provider.parent
                && !self.providers.contains_key(parent.as_str())
            {
                anyhow::bail!(
                    "Provider '{}' references unknown parent '{}'",
                    provider_name,
                    parent.as_str()
                );
            }
            if provider.executor.is_none() && provider.parent.is_none() {
                anyhow::bail!(
                    "Provider '{}' has neither 'executor' nor 'parent' — one is required",
                    provider_name
                );
            }
            if let Some(ref executor) = provider.executor {
                let valid = [Tool::CLAUDE, Tool::COPILOT, Tool::MCP_TESTER];
                if !valid.contains(&executor.as_str()) {
                    anyhow::bail!(
                        "Provider '{}' has unknown executor '{}' — must be one of 'claude', 'copilot', 'mcp-tester'",
                        provider_name,
                        executor
                    );
                }
            }
        }
        // Verify tool entries reference existing providers
        for (tool_name, entries) in &self.tools {
            for entry in entries {
                if !self.providers.contains_key(entry.provider.as_str()) {
                    anyhow::bail!(
                        "Tool '{}' references unknown provider '{}'",
                        tool_name,
                        entry.provider
                    );
                }
            }
        }
        self.agent_github_token.resolve()?;
        // Resolve secrets in providers
        for provider in self.providers.values_mut() {
            if let Some(ref mut key) = provider.access_key {
                key.resolve()?;
            }
        }
        Ok(())
    }

    /// Validate that all tool-name references in role and stage definitions exist in `self.tools`.
    pub fn validate_workflow_refs(&self, workflow: &WorkflowConfig) -> anyhow::Result<()> {
        for (role_name, role_def) in &workflow.roles {
            let Some(ref tool) = role_def.tool else {
                anyhow::bail!("Role '{}' has no tool defined", role_name);
            };
            if !self.tools.contains_key(tool.as_str()) {
                anyhow::bail!(
                    "Role '{}' references unknown tool '{}' (not in [tools])",
                    role_name,
                    tool
                );
            }
        }
        for (pname, pipeline) in &workflow.pipelines {
            for (sname, stage) in &pipeline.stages {
                if let Some(ref tool) = stage.tool
                    && !self.tools.contains_key(tool.as_str())
                {
                    anyhow::bail!(
                        "Stage '{}/{}' references unknown tool '{}' (not in [tools])",
                        pname,
                        sname,
                        tool
                    );
                }
            }
        }
        Ok(())
    }

    /// Determine the effective tool name for a stage.
    ///
    /// Precedence: stage.tool → role.tool
    pub fn resolve_tool_name(
        &self,
        stage_def: &StageDefinition,
        workflow: &WorkflowConfig,
    ) -> anyhow::Result<String> {
        if let Some(ref tool) = stage_def.tool {
            return Ok(tool.clone());
        }
        if let Some(role_name) = stage_def.role_name()
            && let Some(role_def) = workflow.role_definition(role_name)
            && let Some(ref tool) = role_def.tool
        {
            return Ok(tool.clone());
        }
        anyhow::bail!(
            "No tool found for stage {:?} with role {:?}",
            stage_def,
            stage_def.role_name()
        );
    }

    /// Resolve all providers by flattening inheritance chains.
    ///
    /// Returns an `IndexMap` from provider to `ResolvedProvider`.
    pub fn resolve_providers(&self) -> anyhow::Result<IndexMap<Provider, ResolvedProvider>> {
        let mut resolved = IndexMap::new();
        for provider in self.providers.keys() {
            let rp = self.resolve_single_provider(provider.clone(), &mut Vec::new())?;
            resolved.insert(provider.clone(), rp);
        }
        Ok(resolved)
    }

    fn resolve_single_provider(
        &self,
        provider: Provider,
        visited: &mut Vec<Provider>,
    ) -> anyhow::Result<ResolvedProvider> {
        if visited.contains(&provider) {
            anyhow::bail!("Circular parent reference detected in provider '{}'", provider.as_str());
        }
        visited.push(provider.clone());

        let def = self
            .providers
            .get(&provider)
            .ok_or_else(|| anyhow::anyhow!("Provider '{}' not found", provider.as_str()))?;

        if let Some(ref parent_name) = def.parent {
            let parent = self.resolve_single_provider(parent_name.clone(), visited)?;
            Ok(ResolvedProvider {
                provider: provider.clone(),
                executor: def.executor.clone().unwrap_or(parent.executor),
                priority: def.priority.unwrap_or(parent.priority),
                plan_mode: def.plan_mode.unwrap_or(parent.plan_mode),
                access_key: def.access_key.clone().or(parent.access_key),
            })
        } else {
            let executor = def.executor.clone().ok_or_else(|| {
                anyhow::anyhow!("Provider '{}' has no executor and no parent", provider)
            })?;
            Ok(ResolvedProvider {
                provider: provider.clone(),
                executor,
                priority: def.priority.unwrap_or(10),
                plan_mode: def.plan_mode.unwrap_or(false),
                access_key: def.access_key.clone(),
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use indexmap::IndexMap;

    /// Helper: build a minimal ZbobrDispatcherConfig with given providers and tools.
    fn make_config(
        providers: IndexMap<Provider, ProviderDefinition>,
        tools: IndexMap<String, Vec<ToolEntry>>,
    ) -> ZbobrDispatcherConfig {
        ZbobrDispatcherConfig {
            providers,
            tools,
            ..Default::default()
        }
    }

    // ── resolve_providers tests ──────────────────────────────────────────

    #[test]
    fn resolve_providers_basic() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        assert_eq!(resolved.len(), 1);
        let rp = &resolved[&Provider::new("claude")];
        assert_eq!(rp.provider.as_str(), "claude");
        assert_eq!(rp.executor, "claude");
        assert_eq!(rp.priority, 10);
        assert!(!rp.plan_mode);
        assert!(rp.access_key.is_none());
    }

    #[test]
    fn resolve_providers_single_level_inheritance() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude_base"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(Provider::new("claude_child"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("claude_base")),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved[&Provider::new("claude_child")];
        assert_eq!(child.executor, "claude");
    }

    #[test]
    fn resolve_providers_multi_level_chain() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("grandparent"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(Provider::new("parent"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("grandparent")),
                priority: None,
                plan_mode: Some(true),
                access_key: None,
            },
        );
        providers.insert(Provider::new("child"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("parent")),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved[&Provider::new("child")];
        assert_eq!(child.executor, "claude");
        assert!(child.plan_mode);
    }

    #[test]
    fn resolve_providers_circular_reference() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("a"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("b")),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(Provider::new("b"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("a")),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let err = config.resolve_providers().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("circular"),
            "Expected 'circular' in error: {msg}"
        );
    }

    #[test]
    fn resolve_providers_child_overrides_parent() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("base"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: Some(false),
                access_key: None,
            },
        );
        providers.insert(Provider::new("child"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("base")),
                priority: Some(5),
                plan_mode: Some(true),
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved[&Provider::new("child")];
        assert_eq!(child.executor, "claude");
        assert_eq!(child.priority, 5);
        assert!(child.plan_mode);
    }

    // ── validate tests ──────────────────────────────────────────────────

    #[test]
    fn validate_valid_config() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert("smart".to_string(),
            vec![ToolEntry {
                provider: Provider::new("claude"),
                model: "opus".parse().unwrap(),
                priority: None,
            }],
        );
        let mut config = make_config(providers, tools);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn validate_unknown_parent() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("child"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("nonexistent")),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut config = make_config(providers, IndexMap::new());
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("unknown parent"),
            "Expected 'unknown parent' in error: {msg}"
        );
    }

    #[test]
    fn validate_no_executor_no_parent() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("broken"),
            ProviderDefinition {
                executor: None,
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut config = make_config(providers, IndexMap::new());
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("neither 'executor' nor 'parent'"),
            "Expected \"neither 'executor' nor 'parent'\" in error: {msg}"
        );
    }

    #[test]
    fn validate_tool_references_unknown_provider() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert("smart".to_string(),
            vec![ToolEntry {
                provider: Provider::new("ghost"),
                model: "opus".parse().unwrap(),
                priority: None,
            }],
        );
        let mut config = make_config(providers, tools);
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("unknown provider"),
            "Expected 'unknown provider' in error: {msg}"
        );
    }

    // ── resolve_tool_name tests ─────────────────────────────────────────

    fn make_workflow_with_role(role_name: &str, tool: Option<String>) -> WorkflowConfig {
        let mut roles = IndexMap::new();
        roles.insert(
            role_name.to_string(),
            RoleDefinition {
                mcp: None,
                prompt: None,
                tool,
            },
        );
        WorkflowConfig {
            prompts_dir: None,
            roles,
            pipelines: HashMap::new(),
        }
    }

    #[test]
    fn resolve_tool_name_stage_overrides() {
        let stage = StageDefinition {
            tool: Some("stage-tool".to_string()),
            role: Some("worker".to_string().into()),
            ..Default::default()
        };
        let workflow = make_workflow_with_role("worker", Some("role-tool".to_string()));
        let config = ZbobrDispatcherConfig::default();
        assert_eq!(
            config.resolve_tool_name(&stage, &workflow).unwrap(),
            "stage-tool"
        );
    }

    #[test]
    fn resolve_tool_name_falls_back_to_role() {
        let stage = StageDefinition {
            tool: None,
            role: Some("worker".to_string().into()),
            ..Default::default()
        };
        let workflow = make_workflow_with_role("worker", Some("role-tool".to_string()));
        let config = ZbobrDispatcherConfig::default();
        assert_eq!(
            config.resolve_tool_name(&stage, &workflow).unwrap(),
            "role-tool"
        );
    }

    #[test]
    fn resolve_tool_name_errors_when_no_tool() {
        let stage = StageDefinition {
            tool: None,
            role: Some("worker".to_string().into()),
            ..Default::default()
        };
        let workflow = make_workflow_with_role("worker", None);
        let config = ZbobrDispatcherConfig::default();
        assert!(config.resolve_tool_name(&stage, &workflow).is_err());
    }

    #[test]
    fn resolve_tool_name_errors_when_no_role() {
        let stage = StageDefinition {
            tool: None,
            role: Some("nonexistent".to_string().into()),
            ..Default::default()
        };
        let workflow = WorkflowConfig::default();
        let config = ZbobrDispatcherConfig::default();
        assert!(config.resolve_tool_name(&stage, &workflow).is_err());
    }

    // ── resolve_providers – priority inheritance ────────────────────────

    #[test]
    fn resolve_providers_inherits_priority_from_parent() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("base"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: Some(3),
                plan_mode: None,
                access_key: None,
            },
        );
        providers.insert(Provider::new("child"),
            ProviderDefinition {
                executor: None,
                parent: Some(Provider::new("base")),
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let config = make_config(providers, IndexMap::new());
        let resolved = config.resolve_providers().unwrap();

        let child = &resolved[&Provider::new("child")];
        assert_eq!(
            child.priority, 3,
            "Child should inherit parent's priority (3), not default (10)"
        );
    }

    // ── validate – unknown executor ─────────────────────────────────────

    // ── validate – global tool check (removed — global tool no longer exists) ──

    // ── validate_workflow_refs tests ─────────────────────────────────────

    #[test]
    fn validate_workflow_refs_rejects_unknown_role_tool() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert("smart".to_string(),
            vec![ToolEntry {
                provider: Provider::new("claude"),
                model: "opus".parse().unwrap(),
                priority: None,
            }],
        );
        let config = make_config(providers, tools);
        let workflow = make_workflow_with_role("worker", Some("nonexistent".to_string()));
        let err = config.validate_workflow_refs(&workflow).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("Role 'worker' references unknown tool"),
            "Expected role unknown tool error: {msg}"
        );
    }

    #[test]
    fn validate_workflow_refs_rejects_unknown_stage_tool() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert("smart".to_string(),
            vec![ToolEntry {
                provider: Provider::new("claude"),
                model: "opus".parse().unwrap(),
                priority: None,
            }],
        );
        let config = make_config(providers, tools);

        let mut stages = IndexMap::new();
        stages.insert(
            Stage::from("working"),
            StageDefinition {
                role: Some("worker".to_string().into()),
                tool: Some("bad".to_string()),
                ..Default::default()
            },
        );
        let mut pipelines = HashMap::new();
        pipelines.insert(Pipeline::Main, PipelineConfig { stages });
        let workflow = WorkflowConfig {
            prompts_dir: None,
            roles: IndexMap::new(),
            pipelines,
        };
        let err = config.validate_workflow_refs(&workflow).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("Stage") && msg.contains("references unknown tool"),
            "Expected stage unknown tool error: {msg}"
        );
    }

    #[test]
    fn validate_workflow_refs_passes_valid_refs() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert("smart".to_string(),
            vec![ToolEntry {
                provider: Provider::new("claude"),
                model: "opus".parse().unwrap(),
                priority: None,
            }],
        );
        let config = make_config(providers, tools);

        let mut stages = IndexMap::new();
        stages.insert(
            Stage::from("working"),
            StageDefinition {
                role: Some("worker".to_string().into()),
                tool: Some("smart".to_string()),
                ..Default::default()
            },
        );
        let mut pipelines = HashMap::new();
        pipelines.insert(Pipeline::Main, PipelineConfig { stages });
        let mut roles = IndexMap::new();
        roles.insert("worker".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: None,
                tool: Some("smart".to_string()),
            },
        );
        let workflow = WorkflowConfig {
            prompts_dir: None,
            roles,
            pipelines,
        };
        assert!(config.validate_workflow_refs(&workflow).is_ok());
    }

    #[test]
    fn validate_workflow_refs_rejects_role_without_tool() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut tools = IndexMap::new();
        tools.insert("smart".to_string(),
            vec![ToolEntry {
                provider: Provider::new("claude"),
                model: "opus".parse().unwrap(),
                priority: None,
            }],
        );
        let config = make_config(providers, tools);

        let mut stages = IndexMap::new();
        stages.insert(
            Stage::from("working"),
            StageDefinition {
                role: Some("worker".to_string().into()),
                tool: None,
                ..Default::default()
            },
        );
        let mut pipelines = HashMap::new();
        pipelines.insert(Pipeline::Main, PipelineConfig { stages });
        let mut roles = IndexMap::new();
        roles.insert("worker".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: None,
                tool: None,
            },
        );
        let workflow = WorkflowConfig {
            prompts_dir: None,
            roles,
            pipelines,
        };
        let err = config.validate_workflow_refs(&workflow).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("Role 'worker' has no tool defined"),
            "Expected role no tool error: {msg}"
        );
    }

    // ── validate – unknown executor ─────────────────────────────────────

    #[test]
    fn validate_unknown_executor() {
        let mut providers = IndexMap::new();
        providers.insert(Provider::new("bad"),
            ProviderDefinition {
                executor: Some("invalid_executor".to_string()),
                parent: None,
                priority: None,
                plan_mode: None,
                access_key: None,
            },
        );
        let mut config = make_config(providers, IndexMap::new());
        let err = config.validate().unwrap_err();
        let msg = err.to_string().to_lowercase();
        assert!(
            msg.contains("unknown executor"),
            "Expected 'unknown executor' in error: {msg}"
        );
    }

    // ── ToolEntry priority serde round-trips ─────────────────────────────

    #[test]
    fn tool_entry_priority_deserializes_from_toml() {
        let toml_str = r#"
[dispatcher.tools]
developer = [
  { provider = "claude", model = "claude-opus-4.6", priority = 0 }
]
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            dispatcher: Dispatcher,
        }
        #[derive(serde::Deserialize)]
        struct Dispatcher {
            tools: IndexMap<String, Vec<ToolEntry>>,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let entry = &root.dispatcher.tools["developer"][0];
        assert_eq!(entry.priority, Some(0));
    }

    #[test]
    fn tool_entry_priority_defaults_to_none() {
        let toml_str = r#"
[dispatcher.tools]
developer = [
  { provider = "claude", model = "claude-opus-4.6" }
]
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            dispatcher: Dispatcher,
        }
        #[derive(serde::Deserialize)]
        struct Dispatcher {
            tools: IndexMap<String, Vec<ToolEntry>>,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let entry = &root.dispatcher.tools["developer"][0];
        assert_eq!(entry.priority, None);
    }

    #[test]
    fn tool_entry_priority_none_skipped_in_serialization() {
        let entry = ToolEntry {
            provider: Provider::new("claude"),
            model: "claude-opus-4.6".parse().unwrap(),
            priority: None,
        };
        let serialized = toml::to_string(&entry).unwrap();
        assert!(
            !serialized.contains("priority"),
            "priority should be absent when None, got: {serialized}"
        );
    }

    #[test]
    fn tool_entry_priority_some_included_in_serialization() {
        let entry = ToolEntry {
            provider: Provider::new("copilot"),
            model: "claude-sonnet-4.6".parse().unwrap(),
            priority: Some(5),
        };
        let serialized = toml::to_string(&entry).unwrap();
        assert!(
            serialized.contains("priority = 5"),
            "priority = 5 should be present, got: {serialized}"
        );
    }

    // ── resolve_paths tests ─────────────────────────────────────────────

    #[test]
    fn role_definition_resolve_paths_makes_prompt_absolute() {
        let role = RoleDefinition {
            mcp: None,
            prompt: Some(PathBuf::from("prompts/reviewer.md")),
            tool: None,
        };
        let resolved = role.resolve_paths(std::path::Path::new("/shared/configs"));
        assert_eq!(
            resolved.prompt.unwrap(),
            PathBuf::from("/shared/configs/prompts/reviewer.md")
        );
    }

    #[test]
    fn role_definition_resolve_paths_preserves_absolute() {
        let role = RoleDefinition {
            mcp: None,
            prompt: Some(PathBuf::from("/abs/prompt.md")),
            tool: None,
        };
        let resolved = role.resolve_paths(std::path::Path::new("/other"));
        assert_eq!(resolved.prompt.unwrap(), PathBuf::from("/abs/prompt.md"));
    }

    #[test]
    fn stage_definition_resolve_paths_resolves_all_prompt_fields() {
        let stage = StageDefinition {
            role: Some("worker".to_string().into()),
            role_prompt: Some(PathBuf::from("worker.md")),
            prompts: Some(vec![
                PathBuf::from("common.md"),
                PathBuf::from("/abs/special.md"),
            ]),
            ..Default::default()
        };
        let resolved = stage.resolve_paths(std::path::Path::new("/shared"));
        assert_eq!(
            resolved.role_prompt.unwrap(),
            PathBuf::from("/shared/worker.md")
        );
        let prompts = resolved.prompts.as_deref().unwrap();
        assert_eq!(prompts[0], PathBuf::from("/shared/common.md"));
        assert_eq!(prompts[1], PathBuf::from("/abs/special.md"));
    }

    #[test]
    fn pipeline_config_resolve_paths_resolves_stage_prompts() {
        let mut stages = IndexMap::new();
        stages.insert(
            Stage::from("review"),
            StageDefinition {
                role: Some("reviewer".to_string().into()),
                role_prompt: Some(PathBuf::from("review.md")),
                prompts: Some(vec![PathBuf::from("common.md")]),
                ..Default::default()
            },
        );
        let pipeline = PipelineConfig { stages };
        let resolved = pipeline.resolve_paths(std::path::Path::new("/base"));
        let stage = resolved.stage("review").unwrap();
        assert_eq!(
            stage.role_prompt.as_ref().unwrap(),
            &PathBuf::from("/base/review.md")
        );
        assert_eq!(
            stage.prompts.as_deref().unwrap()[0],
            PathBuf::from("/base/common.md")
        );
    }

    #[test]
    fn workflow_toml_resolve_paths_resolves_nested_prompt_fields() {
        let mut roles = IndexMap::new();
        roles.insert("reviewer".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: Some(PathBuf::from("reviewer.md")),
                tool: None,
            },
        );
        let mut stages = IndexMap::new();
        stages.insert(
            Stage::from("review"),
            StageDefinition {
                role: Some("reviewer".to_string().into()),
                role_prompt: Some(PathBuf::from("review_stage.md")),
                prompts: Some(vec![PathBuf::from("common.md")]),
                ..Default::default()
            },
        );
        let mut pipelines = HashMap::new();
        pipelines.insert(Pipeline::Main, PipelineConfig { stages });

        let toml = WorkflowToml {
            prompts_dir: Some(PathBuf::from("prompts")),
            roles: Some(roles),
            pipelines: Some(pipelines),
        };
        let resolved = toml.resolve_paths(std::path::Path::new("/shared"));

        // prompts_dir resolved
        assert_eq!(
            resolved.prompts_dir.unwrap(),
            PathBuf::from("/shared/prompts")
        );
        // role prompt resolved against prompts_dir
        let role = &resolved.roles.as_ref().unwrap()["reviewer"];
        assert_eq!(
            role.prompt.as_ref().unwrap(),
            &PathBuf::from("/shared/prompts/reviewer.md")
        );
        // stage prompts resolved against prompts_dir
        let pipeline = &resolved.pipelines.as_ref().unwrap()[&Pipeline::Main];
        let stage = pipeline.stage("review").unwrap();
        assert_eq!(
            stage.role_prompt.as_ref().unwrap(),
            &PathBuf::from("/shared/prompts/review_stage.md")
        );
        assert_eq!(
            stage.prompts.as_deref().unwrap()[0],
            PathBuf::from("/shared/prompts/common.md")
        );
    }

    #[test]
    fn workflow_toml_merge_preserves_resolved_paths_from_base() {
        // Simulate two config files from different directories:
        // Base config (from /shared/) defines workflow with relative prompts.
        // Overlay config (from /project/) has no workflow section.
        // After per-file resolution + merge, the base paths should stay anchored to /shared/.
        let mut roles = IndexMap::new();
        roles.insert("reviewer".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: Some(PathBuf::from("reviewer.md")),
                tool: None,
            },
        );
        let base = WorkflowToml {
            prompts_dir: Some(PathBuf::from("prompts")),
            roles: Some(roles),
            pipelines: None,
        };
        let base_resolved = base.resolve_paths(std::path::Path::new("/shared"));

        // Overlay has no workflow fields
        let overlay = WorkflowToml::default();
        let overlay_resolved = overlay.resolve_paths(std::path::Path::new("/project"));

        let merged = base_resolved.merge_toml(overlay_resolved);

        // Base paths should remain anchored to /shared/
        assert_eq!(
            merged.prompts_dir.unwrap(),
            PathBuf::from("/shared/prompts")
        );
        let role = &merged.roles.as_ref().unwrap()["reviewer"];
        assert_eq!(
            role.prompt.as_ref().unwrap(),
            &PathBuf::from("/shared/prompts/reviewer.md")
        );
    }

    // ── merge_toml map-merge semantics ──────────────────────────────────

    #[test]
    fn workflow_toml_merge_roles_key_wise() {
        // Base config defines two roles; overlay overrides only one.
        // The unmodified role from base must survive the merge.
        let mut base_roles = IndexMap::new();
        base_roles.insert("reviewer".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: Some(PathBuf::from("/shared/reviewer.md")),
                tool: None,
            },
        );
        base_roles.insert("worker".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: Some(PathBuf::from("/shared/worker.md")),
                tool: None,
            },
        );
        let base = WorkflowToml {
            prompts_dir: None,
            roles: Some(base_roles),
            pipelines: None,
        };

        // Overlay only overrides "reviewer", with a different prompt.
        let mut overlay_roles = IndexMap::new();
        overlay_roles.insert("reviewer".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: Some(PathBuf::from("/project/reviewer_override.md")),
                tool: None,
            },
        );
        let overlay = WorkflowToml {
            prompts_dir: None,
            roles: Some(overlay_roles),
            pipelines: None,
        };

        let merged = base.merge_toml(overlay);
        let roles = merged.roles.unwrap();

        // "reviewer" is overridden by the overlay.
        assert_eq!(
            roles["reviewer"].prompt.as_ref().unwrap(),
            &PathBuf::from("/project/reviewer_override.md")
        );
        // "worker" survives from the base config unchanged.
        assert_eq!(
            roles["worker"].prompt.as_ref().unwrap(),
            &PathBuf::from("/shared/worker.md")
        );
    }

    #[test]
    fn workflow_toml_merge_pipelines_key_wise() {
        // Base config defines two pipelines; overlay overrides only one.
        let mut base_pipelines = HashMap::new();
        let mut main_stages = IndexMap::new();
        main_stages.insert(
            Stage::from("planning"),
            StageDefinition {
                role: Some("planner".to_string().into()),
                ..Default::default()
            },
        );
        base_pipelines.insert(
            Pipeline::Main,
            PipelineConfig {
                stages: main_stages,
            },
        );
        let mut fix_stages = IndexMap::new();
        fix_stages.insert(
            Stage::from("fixing"),
            StageDefinition {
                role: Some("worker".to_string().into()),
                ..Default::default()
            },
        );
        base_pipelines.insert(
            Pipeline::Custom("fix".to_string()),
            PipelineConfig { stages: fix_stages },
        );

        let base = WorkflowToml {
            prompts_dir: None,
            roles: None,
            pipelines: Some(base_pipelines),
        };

        // Overlay only overrides the Main pipeline.
        let mut overlay_stages = IndexMap::new();
        overlay_stages.insert(
            Stage::from("planning"),
            StageDefinition {
                role: Some("senior_planner".to_string().into()),
                ..Default::default()
            },
        );
        let mut overlay_pipelines = HashMap::new();
        overlay_pipelines.insert(
            Pipeline::Main,
            PipelineConfig {
                stages: overlay_stages,
            },
        );
        let overlay = WorkflowToml {
            prompts_dir: None,
            roles: None,
            pipelines: Some(overlay_pipelines),
        };

        let merged = base.merge_toml(overlay);
        let pipelines = merged.pipelines.unwrap();

        // Main pipeline is overridden by the overlay.
        let main = &pipelines[&Pipeline::Main];
        assert_eq!(
            main.stage("planning").unwrap().role.as_deref().unwrap(),
            "senior_planner"
        );
        // Fix pipeline survives from the base config unchanged.
        let fix = &pipelines[&Pipeline::Custom("fix".to_string())];
        assert_eq!(
            fix.stage("fixing").unwrap().role.as_deref().unwrap(),
            "worker"
        );
    }

    #[test]
    fn dispatcher_toml_merge_providers_key_wise() {
        // Base config defines two providers; overlay adds one and overrides one.
        let mut base_providers = IndexMap::new();
        base_providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: Some(10),
                plan_mode: None,
                access_key: None,
            },
        );
        base_providers.insert(Provider::new("copilot"),
            ProviderDefinition {
                executor: Some("copilot".to_string()),
                parent: None,
                priority: Some(5),
                plan_mode: None,
                access_key: None,
            },
        );

        let base_toml = ZbobrDispatcherConfigToml {
            providers: Some(base_providers),
            ..Default::default()
        };

        // Overlay overrides "claude" with higher priority and adds "gpt".
        let mut overlay_providers = IndexMap::new();
        overlay_providers.insert(Provider::new("claude"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: Some(20),
                plan_mode: None,
                access_key: None,
            },
        );
        overlay_providers.insert(Provider::new("gpt"),
            ProviderDefinition {
                executor: Some("openai".to_string()),
                parent: None,
                priority: Some(15),
                plan_mode: None,
                access_key: None,
            },
        );

        let overlay_toml = ZbobrDispatcherConfigToml {
            providers: Some(overlay_providers),
            ..Default::default()
        };

        let merged = base_toml.merge_toml(overlay_toml);
        let providers = merged.providers.unwrap();

        // "claude" is overridden with priority 20.
        assert_eq!(providers["claude"].priority, Some(20));
        // "copilot" survives from the base config.
        assert_eq!(providers["copilot"].priority, Some(5));
        // "gpt" is added by the overlay.
        assert_eq!(providers["gpt"].executor.as_deref(), Some("openai"));
        assert_eq!(providers.len(), 3);
    }

    #[test]
    fn provider_partial_patch_preserves_base_fields() {
        // Base defines a full provider; overlay only patches priority.
        // The overlay must NOT lose executor or other fields from base.
        let mut base_providers = IndexMap::new();
        base_providers.insert(Provider::new("shared"),
            ProviderDefinition {
                executor: Some("claude".to_string()),
                parent: None,
                priority: Some(10),
                plan_mode: Some(false),
                access_key: None,
            },
        );

        let base_toml = ZbobrDispatcherConfigToml {
            providers: Some(base_providers),
            ..Default::default()
        };

        // Overlay only overrides priority — executor and plan_mode are not restated.
        let mut overlay_providers = IndexMap::new();
        overlay_providers.insert(Provider::new("shared"),
            ProviderDefinition {
                executor: None,
                parent: None,
                priority: Some(20),
                plan_mode: None,
                access_key: None,
            },
        );

        let overlay_toml = ZbobrDispatcherConfigToml {
            providers: Some(overlay_providers),
            ..Default::default()
        };

        let merged = base_toml.merge_toml(overlay_toml);
        let providers = merged.providers.unwrap();

        assert_eq!(
            providers["shared"].priority,
            Some(20),
            "priority should be overridden"
        );
        assert_eq!(
            providers["shared"].executor.as_deref(),
            Some("claude"),
            "executor should be preserved from base"
        );
        assert_eq!(
            providers["shared"].plan_mode,
            Some(false),
            "plan_mode should be preserved from base"
        );
    }

    #[test]
    fn role_partial_patch_preserves_base_fields() {
        // Base defines a role with mcp and prompt; overlay only patches tool.
        // mcp and prompt must survive because overlay uses mcp: None (field absent).
        use crate::config_tools::McpTool;
        let mut base_roles = IndexMap::new();
        base_roles.insert("worker".to_string(),
            RoleDefinition {
                mcp: Some(vec![McpTool::ReportSuccess]),
                prompt: Some(PathBuf::from("/shared/worker.md")),
                tool: None,
            },
        );

        let base = WorkflowToml {
            prompts_dir: None,
            roles: Some(base_roles),
            pipelines: None,
        };

        // Overlay sets only tool; mcp is None (not specified) so base mcp survives.
        let mut overlay_roles = IndexMap::new();
        overlay_roles.insert("worker".to_string(),
            RoleDefinition {
                mcp: None,
                prompt: None,
                tool: Some("fast-tool".to_string()),
            },
        );

        let overlay = WorkflowToml {
            prompts_dir: None,
            roles: Some(overlay_roles),
            pipelines: None,
        };

        let merged = base.merge_toml(overlay);
        let roles = merged.roles.unwrap();

        assert_eq!(
            roles["worker"].tool.as_deref(),
            Some("fast-tool"),
            "tool should be set by overlay"
        );
        assert_eq!(
            roles["worker"].prompt.as_ref().unwrap(),
            &PathBuf::from("/shared/worker.md"),
            "prompt should be preserved from base"
        );
        assert!(
            roles["worker"].mcp.as_ref().is_some_and(|v| !v.is_empty()),
            "mcp should be preserved from base"
        );
    }

    #[test]
    fn role_mcp_cleared_by_empty_list_overlay() {
        // An overlay that explicitly sets mcp = [] must clear the base mcp list.
        use crate::config_tools::McpTool;
        let mut base_roles = IndexMap::new();
        base_roles.insert("worker".to_string(),
            RoleDefinition {
                mcp: Some(vec![McpTool::ReportSuccess]),
                prompt: None,
                tool: None,
            },
        );
        let base = WorkflowToml {
            prompts_dir: None,
            roles: Some(base_roles),
            pipelines: None,
        };

        // Overlay explicitly sets mcp = [] (Some(vec![])) to clear the list.
        let mut overlay_roles = IndexMap::new();
        overlay_roles.insert("worker".to_string(),
            RoleDefinition {
                mcp: Some(vec![]),
                prompt: None,
                tool: None,
            },
        );
        let overlay = WorkflowToml {
            prompts_dir: None,
            roles: Some(overlay_roles),
            pipelines: None,
        };

        let merged = base.merge_toml(overlay);
        let roles = merged.roles.unwrap();

        assert!(
            roles["worker"].mcp.as_ref().is_some_and(|v| v.is_empty()),
            "mcp should be cleared by explicit empty-list overlay"
        );
    }

    #[test]
    fn pipeline_partial_stage_patch_preserves_other_stages() {
        // Base defines a pipeline with two stages; overlay patches only one stage's role
        // while leaving the other stage and the patched stage's tool intact.
        let mut base_stages = IndexMap::new();
        base_stages.insert(
            Stage::from("planning"),
            StageDefinition {
                role: Some("planner".to_string().into()),
                tool: Some("fast".to_string()),
                ..Default::default()
            },
        );
        base_stages.insert(
            Stage::from("working"),
            StageDefinition {
                role: Some("worker".to_string().into()),
                ..Default::default()
            },
        );

        let mut base_pipelines = HashMap::new();
        base_pipelines.insert(
            Pipeline::Main,
            PipelineConfig {
                stages: base_stages,
            },
        );

        let base = WorkflowToml {
            prompts_dir: None,
            roles: None,
            pipelines: Some(base_pipelines),
        };

        // Overlay patches "planning" stage: changes role but leaves tool as None (not restated).
        let mut overlay_stages = IndexMap::new();
        overlay_stages.insert(
            Stage::from("planning"),
            StageDefinition {
                role: Some("senior_planner".to_string().into()),
                tool: None,
                ..Default::default()
            },
        );
        let mut overlay_pipelines = HashMap::new();
        overlay_pipelines.insert(
            Pipeline::Main,
            PipelineConfig {
                stages: overlay_stages,
            },
        );

        let overlay = WorkflowToml {
            prompts_dir: None,
            roles: None,
            pipelines: Some(overlay_pipelines),
        };

        let merged = base.merge_toml(overlay);
        let pipelines = merged.pipelines.unwrap();
        let main = &pipelines[&Pipeline::Main];

        assert_eq!(
            main.stage("planning").unwrap().role.as_deref().unwrap(),
            "senior_planner",
            "planning role should be overridden"
        );
        assert_eq!(
            main.stage("planning").unwrap().tool.as_deref(),
            Some("fast"),
            "planning tool should be preserved from base"
        );
        assert_eq!(
            main.stage("working").unwrap().role.as_deref().unwrap(),
            "worker",
            "working stage should survive unchanged from base"
        );
    }

    #[test]
    fn stage_prompts_cleared_by_empty_list_overlay() {
        // An overlay that explicitly sets prompts = [] must clear the base prompts list.
        let mut base_stages = IndexMap::new();
        base_stages.insert(
            Stage::from("planning"),
            StageDefinition {
                role: Some("planner".to_string().into()),
                prompts: Some(vec![PathBuf::from("/shared/common.md")]),
                ..Default::default()
            },
        );
        let mut base_pipelines = HashMap::new();
        base_pipelines.insert(
            Pipeline::Main,
            PipelineConfig {
                stages: base_stages,
            },
        );

        let base = WorkflowToml {
            prompts_dir: None,
            roles: None,
            pipelines: Some(base_pipelines),
        };

        // Overlay explicitly sets prompts = [] to clear the inherited list.
        let mut overlay_stages = IndexMap::new();
        overlay_stages.insert(
            Stage::from("planning"),
            StageDefinition {
                role: None,
                prompts: Some(vec![]),
                ..Default::default()
            },
        );
        let mut overlay_pipelines = HashMap::new();
        overlay_pipelines.insert(
            Pipeline::Main,
            PipelineConfig {
                stages: overlay_stages,
            },
        );

        let overlay = WorkflowToml {
            prompts_dir: None,
            roles: None,
            pipelines: Some(overlay_pipelines),
        };

        let merged = base.merge_toml(overlay);
        let pipelines = merged.pipelines.unwrap();
        let main = &pipelines[&Pipeline::Main];

        assert!(
            main.stage("planning")
                .unwrap()
                .prompts
                .as_ref()
                .is_some_and(|v| v.is_empty()),
            "prompts should be cleared by explicit empty-list overlay"
        );
    }

    // ── Option<Vec<T>> TOML deserialization round-trip tests ─────────────

    #[test]
    fn role_mcp_missing_deserializes_as_none() {
        let toml_str = r#"
[workflow.roles.worker]
tool = "developer"
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            workflow: WorkflowToml,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let role = &root.workflow.roles.unwrap()["worker"];
        assert!(
            role.mcp.is_none(),
            "missing mcp field should deserialize as None"
        );
    }

    #[test]
    fn role_mcp_empty_list_deserializes_as_some_empty() {
        let toml_str = r#"
[workflow.roles.worker]
mcp = []
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            workflow: WorkflowToml,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let role = &root.workflow.roles.unwrap()["worker"];
        assert!(
            role.mcp.as_ref().is_some_and(|v| v.is_empty()),
            "mcp = [] should deserialize as Some(vec![])"
        );
    }

    #[test]
    fn role_mcp_populated_list_deserializes_as_some_with_entries() {
        let toml_str = r#"
[workflow.roles.worker]
mcp = ["report_success", "report_failure"]
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            workflow: WorkflowToml,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let role = &root.workflow.roles.unwrap()["worker"];
        let mcp = role.mcp.as_ref().unwrap();
        assert_eq!(mcp.len(), 2);
        assert_eq!(mcp[0], McpTool::ReportSuccess);
        assert_eq!(mcp[1], McpTool::ReportFailure);
    }

    #[test]
    fn stage_prompts_missing_deserializes_as_none() {
        let toml_str = r#"
[workflow.pipelines.main.stages.planning]
role = "planner"
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            workflow: WorkflowToml,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let pipelines = root.workflow.pipelines.unwrap();
        let stage = &pipelines[&Pipeline::Main].stages["planning"];
        assert!(
            stage.prompts.is_none(),
            "missing prompts should deserialize as None"
        );
    }

    #[test]
    fn stage_prompts_empty_list_deserializes_as_some_empty() {
        let toml_str = r#"
[workflow.pipelines.main.stages.planning]
role = "planner"
prompts = []
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            workflow: WorkflowToml,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let pipelines = root.workflow.pipelines.unwrap();
        let stage = &pipelines[&Pipeline::Main].stages["planning"];
        assert!(
            stage.prompts.as_ref().is_some_and(|v| v.is_empty()),
            "prompts = [] should deserialize as Some(vec![])"
        );
    }

    #[test]
    fn stage_prompts_populated_list_deserializes_as_some_with_entries() {
        let toml_str = r#"
[workflow.pipelines.main.stages.planning]
role = "planner"
prompts = ["common.md", "planning.md"]
"#;
        #[derive(serde::Deserialize)]
        struct Root {
            workflow: WorkflowToml,
        }
        let root: Root = toml::from_str(toml_str).unwrap();
        let pipelines = root.workflow.pipelines.unwrap();
        let stage = &pipelines[&Pipeline::Main].stages["planning"];
        let prompts = stage.prompts.as_ref().unwrap();
        assert_eq!(prompts.len(), 2);
        assert_eq!(prompts[0], PathBuf::from("common.md"));
        assert_eq!(prompts[1], PathBuf::from("planning.md"));
    }

    // ── Tools map merge test (IndexMap<String, Vec<ToolEntry>>) ─────────

    #[test]
    fn dispatcher_toml_merge_tools_key_wise_with_wholesale_list_replacement() {
        let mut base_tools = IndexMap::new();
        base_tools.insert("developer".to_string(),
            vec![
                ToolEntry {
                    provider: Provider::new("claude"),
                    model: "claude-opus-4.6".parse().unwrap(),
                    priority: None,
                },
                ToolEntry {
                    provider: Provider::new("copilot"),
                    model: "claude-sonnet-4.6".parse().unwrap(),
                    priority: Some(5),
                },
            ],
        );
        base_tools.insert("reviewer".to_string(),
            vec![ToolEntry {
                provider: Provider::new("claude"),
                model: "claude-opus-4.6".parse().unwrap(),
                priority: None,
            }],
        );

        let base_toml = ZbobrDispatcherConfigToml {
            tools: Some(base_tools),
            ..Default::default()
        };

        // Overlay replaces "developer" list entirely and adds "tester".
        let mut overlay_tools = IndexMap::new();
        overlay_tools.insert("developer".to_string(),
            vec![ToolEntry {
                provider: Provider::new("gpt"),
                model: "claude-opus-4.6".parse().unwrap(),
                priority: Some(1),
            }],
        );
        overlay_tools.insert("tester".to_string(),
            vec![ToolEntry {
                provider: Provider::new("claude"),
                model: "claude-sonnet-4.6".parse().unwrap(),
                priority: None,
            }],
        );

        let overlay_toml = ZbobrDispatcherConfigToml {
            tools: Some(overlay_tools),
            ..Default::default()
        };

        let merged = base_toml.merge_toml(overlay_toml);
        let tools = merged.tools.unwrap();

        // "developer" list is fully replaced by overlay (1 entry, not 2).
        assert_eq!(tools["developer"].len(), 1);
        assert_eq!(tools["developer"][0].provider, "gpt".into());
        assert_eq!(tools["developer"][0].priority, Some(1));
        // "reviewer" survives unchanged from base.
        assert_eq!(tools["reviewer"].len(), 1);
        assert_eq!(tools["reviewer"][0].provider, "claude".into());
        // "tester" added from overlay.
        assert_eq!(tools["tester"].len(), 1);
        assert_eq!(tools["tester"][0].provider, "claude".into());
        // Total: 3 tool names.
        assert_eq!(tools.len(), 3);
    }

    // ── End-to-end multi-config merge from TOML strings ─────────────────

    #[test]
    fn workflow_toml_end_to_end_merge_from_toml_strings() {
        let base_toml_str = r#"
[workflow.roles.worker]
mcp = ["report_success", "report_failure"]
prompt = "worker.md"

[workflow.roles.reviewer]
mcp = ["report_success"]
prompt = "reviewer.md"

[workflow.pipelines.main.stages.planning]
role = "worker"
prompts = ["common.md", "planning.md"]

[workflow.pipelines.main.stages.working]
role = "worker"
prompts = ["common.md", "working.md"]
"#;

        let overlay_toml_str = r#"
[workflow.roles.worker]
mcp = ["report_success", "report_intermediate", "add_checklist_item"]

[workflow.pipelines.main.stages.planning]
prompts = []
"#;

        #[derive(serde::Deserialize)]
        struct Root {
            workflow: WorkflowToml,
        }

        let base: Root = toml::from_str(base_toml_str).unwrap();
        let overlay: Root = toml::from_str(overlay_toml_str).unwrap();

        let merged = base.workflow.merge_toml(overlay.workflow);

        // Worker role: mcp overridden by overlay (3 entries instead of 2).
        let roles = merged.roles.as_ref().unwrap();
        let worker_mcp = roles["worker"].mcp.as_ref().unwrap();
        assert_eq!(worker_mcp.len(), 3);
        assert_eq!(worker_mcp[0], McpTool::ReportSuccess);
        assert_eq!(worker_mcp[1], McpTool::ReportIntermediate);
        assert_eq!(worker_mcp[2], McpTool::AddChecklistItem);

        // Worker role: prompt inherits from base (overlay didn't specify it).
        assert_eq!(
            roles["worker"].prompt.as_deref(),
            Some(std::path::Path::new("worker.md"))
        );

        // Reviewer role: completely inherited from base (not in overlay).
        let reviewer_mcp = roles["reviewer"].mcp.as_ref().unwrap();
        assert_eq!(reviewer_mcp.len(), 1);
        assert_eq!(reviewer_mcp[0], McpTool::ReportSuccess);
        assert_eq!(
            roles["reviewer"].prompt.as_deref(),
            Some(std::path::Path::new("reviewer.md"))
        );

        // Planning stage: prompts explicitly cleared by overlay.
        let pipelines = merged.pipelines.as_ref().unwrap();
        let main = &pipelines[&Pipeline::Main];
        assert!(
            main.stage("planning")
                .unwrap()
                .prompts
                .as_ref()
                .is_some_and(|v| v.is_empty()),
            "planning prompts should be cleared by empty-list overlay"
        );

        // Planning stage: role inherited from base (overlay didn't specify it).
        assert_eq!(
            main.stage("planning").unwrap().role.as_deref(),
            Some("worker")
        );

        // Working stage: completely inherited from base (not in overlay).
        let working_prompts = main.stage("working").unwrap().prompts.as_ref().unwrap();
        assert_eq!(working_prompts.len(), 2);
        assert_eq!(working_prompts[0], PathBuf::from("common.md"));
        assert_eq!(working_prompts[1], PathBuf::from("working.md"));
    }
}
